# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.health_check200_response import HealthCheck200Response

class TestHealthCheck200Response(unittest.TestCase):
    """HealthCheck200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthCheck200Response:
        """Test HealthCheck200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthCheck200Response`
        """
        model = HealthCheck200Response()
        if include_optional:
            return HealthCheck200Response(
                status = 'ok',
                timestamp = '2026-06-22T14:30:00.000Z',
                version = '1.0.0'
            )
        else:
            return HealthCheck200Response(
                status = 'ok',
                timestamp = '2026-06-22T14:30:00.000Z',
                version = '1.0.0',
        )
        """

    def testHealthCheck200Response(self):
        """Test HealthCheck200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
