# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.update_order_request import UpdateOrderRequest

class TestUpdateOrderRequest(unittest.TestCase):
    """UpdateOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrderRequest:
        """Test UpdateOrderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrderRequest`
        """
        model = UpdateOrderRequest()
        if include_optional:
            return UpdateOrderRequest(
                order_number = '#1042',
                customer_name = 'Anna Jensen',
                customer_email = 'anna@example.dk',
                shipping_address = zippendo.models.create_order_request_shipping_address.createOrder_request_shippingAddress(
                    name = 'Anna Jensen', 
                    attention = 'c/o Reception', 
                    company = 'Jensen Design ApS', 
                    address1 = 'Nørregade 12', 
                    address2 = '2. sal', 
                    city = 'København', 
                    province = 'Hovedstaden', 
                    province_code = 'DK-84', 
                    postal_code = '1165', 
                    country = 'Denmark', 
                    country_code = 'DK', 
                    phone = '+45 12 34 56 78', 
                    email = 'anna@example.dk', ),
                order_lines = [
                    zippendo.models.create_order_request_order_lines_inner.createOrder_request_orderLines_inner(
                        sku = 'SKU-1042-BLK', 
                        name = 'Wool Sweater', 
                        quantity = 2, 
                        unit_price = 499, 
                        total_price = 998, 
                        currency = 'DKK', 
                        weight = 0.5, 
                        weight_unit = 'kg', 
                        variant_id = '44218900291', 
                        product_id = '8123456789', 
                        image_url = 'https://cdn.example.dk/products/sweater.jpg', 
                        hs_code = '611020', 
                        country_of_origin = 'DK', 
                        province_of_origin = 'DK-84', 
                        barcode = '5712345678901', 
                        requires_shipping = True, 
                        taxable = True, 
                        gift_card = False, 
                        vendor = 'Norse Knits', )
                    ],
                subtotal_amount = 998,
                total_amount = 1047,
                currency = 'DKK',
                notes = 'Leave at front desk',
                status = 'processing',
                shipping_rule_id = 'clz9k2f0a0002abcd5678ijkl'
            )
        else:
            return UpdateOrderRequest(
        )
        """

    def testUpdateOrderRequest(self):
        """Test UpdateOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
