# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipping_quote200_response import CreateShippingQuote200Response

class TestCreateShippingQuote200Response(unittest.TestCase):
    """CreateShippingQuote200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShippingQuote200Response:
        """Test CreateShippingQuote200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShippingQuote200Response`
        """
        model = CreateShippingQuote200Response()
        if include_optional:
            return CreateShippingQuote200Response(
                rates = []
            )
        else:
            return CreateShippingQuote200Response(
                rates = [],
        )
        """

    def testCreateShippingQuote200Response(self):
        """Test CreateShippingQuote200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
