# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.get_billing_usage200_response_limits_team_members import GetBillingUsage200ResponseLimitsTeamMembers

class TestGetBillingUsage200ResponseLimitsTeamMembers(unittest.TestCase):
    """GetBillingUsage200ResponseLimitsTeamMembers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingUsage200ResponseLimitsTeamMembers:
        """Test GetBillingUsage200ResponseLimitsTeamMembers
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBillingUsage200ResponseLimitsTeamMembers`
        """
        model = GetBillingUsage200ResponseLimitsTeamMembers()
        if include_optional:
            return GetBillingUsage200ResponseLimitsTeamMembers(
                used = 3,
                limit = 5
            )
        else:
            return GetBillingUsage200ResponseLimitsTeamMembers(
                used = 3,
                limit = 5,
        )
        """

    def testGetBillingUsage200ResponseLimitsTeamMembers(self):
        """Test GetBillingUsage200ResponseLimitsTeamMembers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
