# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_carrier_products200_response_inner_services_inner import ListCarrierProducts200ResponseInnerServicesInner

class TestListCarrierProducts200ResponseInnerServicesInner(unittest.TestCase):
    """ListCarrierProducts200ResponseInnerServicesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCarrierProducts200ResponseInnerServicesInner:
        """Test ListCarrierProducts200ResponseInnerServicesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCarrierProducts200ResponseInnerServicesInner`
        """
        model = ListCarrierProducts200ResponseInnerServicesInner()
        if include_optional:
            return ListCarrierProducts200ResponseInnerServicesInner(
                name = 'Flex delivery',
                service_id = 'A6'
            )
        else:
            return ListCarrierProducts200ResponseInnerServicesInner(
                name = 'Flex delivery',
                service_id = 'A6',
        )
        """

    def testListCarrierProducts200ResponseInnerServicesInner(self):
        """Test ListCarrierProducts200ResponseInnerServicesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
