# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.api.tokens_api import TokensApi


class TestTokensApi(unittest.TestCase):
    """TokensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TokensApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_token(self) -> None:
        """Test case for create_api_token

        Create API keys
        """
        pass

    def test_get_api_token(self) -> None:
        """Test case for get_api_token

        Get API keys
        """
        pass

    def test_list_api_tokens(self) -> None:
        """Test case for list_api_tokens

        List API keys
        """
        pass

    def test_revoke_api_token(self) -> None:
        """Test case for revoke_api_token

        Revoke API keys
        """
        pass

    def test_update_api_token(self) -> None:
        """Test case for update_api_token

        Update API keys
        """
        pass

    def test_verify_api_token(self) -> None:
        """Test case for verify_api_token

        Verify API keys
        """
        pass


if __name__ == '__main__':
    unittest.main()
