# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.split_shipment_parcel_request_parcels_inner import SplitShipmentParcelRequestParcelsInner

class TestSplitShipmentParcelRequestParcelsInner(unittest.TestCase):
    """SplitShipmentParcelRequestParcelsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SplitShipmentParcelRequestParcelsInner:
        """Test SplitShipmentParcelRequestParcelsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SplitShipmentParcelRequestParcelsInner`
        """
        model = SplitShipmentParcelRequestParcelsInner()
        if include_optional:
            return SplitShipmentParcelRequestParcelsInner(
                id = 'prc_5a6b7c8d',
                order_lines = [
                    zippendo.models.batch_split_shipment_request_shipments_inner_order_lines_inner.batchSplitShipment_request_shipments_inner_orderLines_inner(
                        id = 'ol_9c1d2e3f', 
                        quantity = 1, )
                    ]
            )
        else:
            return SplitShipmentParcelRequestParcelsInner(
                order_lines = [
                    zippendo.models.batch_split_shipment_request_shipments_inner_order_lines_inner.batchSplitShipment_request_shipments_inner_orderLines_inner(
                        id = 'ol_9c1d2e3f', 
                        quantity = 1, )
                    ],
        )
        """

    def testSplitShipmentParcelRequestParcelsInner(self):
        """Test SplitShipmentParcelRequestParcelsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
