# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipment201_response_parcels_inner import CreateShipment201ResponseParcelsInner

class TestCreateShipment201ResponseParcelsInner(unittest.TestCase):
    """CreateShipment201ResponseParcelsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShipment201ResponseParcelsInner:
        """Test CreateShipment201ResponseParcelsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShipment201ResponseParcelsInner`
        """
        model = CreateShipment201ResponseParcelsInner()
        if include_optional:
            return CreateShipment201ResponseParcelsInner(
                id = 'prc_5a6b7c8d',
                weight = 2.5,
                weight_unit = 'kg',
                dimensions = zippendo.models.create_shipment_201_response_parcels_inner_dimensions.createShipment_201_response_parcels_inner_dimensions(
                    length = 30, 
                    width = 20, 
                    height = 15, ),
                order_lines = [
                    zippendo.models.create_shipment_201_response_parcels_inner_order_lines_inner.createShipment_201_response_parcels_inner_orderLines_inner(
                        id = 'ol_9c1d2e3f', 
                        sku = 'SKU-1024', 
                        quantity = 2, 
                        description = 'Wool sweater, navy', 
                        unit_price = 299.95, 
                        currency = 'DKK', 
                        vat_percent = 25, 
                        location = 'A-12-3', 
                        country_of_origin = 'DK', 
                        tarrif_number = '61101100', )
                    ],
                tracking_number = '00370724710000012345',
                tracking_url = 'https://tracking.postnord.com/00370724710000012345',
                label_free_code = 'AB12CD34',
                qr_code_link = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
                qr_code_data_uri = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
                qr_code_url = 'https://qr.bring.com/label-free/AB12CD34.png'
            )
        else:
            return CreateShipment201ResponseParcelsInner(
                weight = 2.5,
                weight_unit = 'kg',
                dimensions = zippendo.models.create_shipment_201_response_parcels_inner_dimensions.createShipment_201_response_parcels_inner_dimensions(
                    length = 30, 
                    width = 20, 
                    height = 15, ),
                order_lines = [
                    zippendo.models.create_shipment_201_response_parcels_inner_order_lines_inner.createShipment_201_response_parcels_inner_orderLines_inner(
                        id = 'ol_9c1d2e3f', 
                        sku = 'SKU-1024', 
                        quantity = 2, 
                        description = 'Wool sweater, navy', 
                        unit_price = 299.95, 
                        currency = 'DKK', 
                        vat_percent = 25, 
                        location = 'A-12-3', 
                        country_of_origin = 'DK', 
                        tarrif_number = '61101100', )
                    ],
        )
        """

    def testCreateShipment201ResponseParcelsInner(self):
        """Test CreateShipment201ResponseParcelsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
