# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_orders200_response_data_inner import ListOrders200ResponseDataInner

class TestListOrders200ResponseDataInner(unittest.TestCase):
    """ListOrders200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOrders200ResponseDataInner:
        """Test ListOrders200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOrders200ResponseDataInner`
        """
        model = ListOrders200ResponseDataInner()
        if include_optional:
            return ListOrders200ResponseDataInner(
                id = 'clz9k2f0a0003abcd9012mnop',
                order_number = '#1042',
                customer_name = 'Anna Jensen',
                customer_email = 'anna@example.dk',
                status = 'processing',
                subtotal_amount = 998,
                total_amount = 1047,
                currency = 'DKK',
                shipment_count = 1,
                order_channel = zippendo.models.list_orders_200_response_data_inner_order_channel.listOrders_200_response_data_inner_orderChannel(
                    id = 'clz9k2f0a0001abcd1234efgh', 
                    name = 'Anna's Shopify Store', 
                    type = 'shopify', ),
                created_at = '2026-06-22T14:30:00.000Z',
                updated_at = '2026-06-22T14:30:00.000Z'
            )
        else:
            return ListOrders200ResponseDataInner(
                id = 'clz9k2f0a0003abcd9012mnop',
                order_number = '#1042',
                status = 'processing',
                shipment_count = 1,
                order_channel = zippendo.models.list_orders_200_response_data_inner_order_channel.listOrders_200_response_data_inner_orderChannel(
                    id = 'clz9k2f0a0001abcd1234efgh', 
                    name = 'Anna's Shopify Store', 
                    type = 'shopify', ),
                created_at = '2026-06-22T14:30:00.000Z',
                updated_at = '2026-06-22T14:30:00.000Z',
        )
        """

    def testListOrders200ResponseDataInner(self):
        """Test ListOrders200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
