# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.api.orgs_api import OrgsApi


class TestOrgsApi(unittest.TestCase):
    """OrgsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrgsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_org_logo(self) -> None:
        """Test case for delete_org_logo

        Delete org logo
        """
        pass

    def test_get_org(self) -> None:
        """Test case for get_org

        Get org
        """
        pass

    def test_get_org_branding(self) -> None:
        """Test case for get_org_branding

        Get org branding
        """
        pass

    def test_get_org_logo(self) -> None:
        """Test case for get_org_logo

        Download org logo
        """
        pass

    def test_update_org(self) -> None:
        """Test case for update_org

        Update org
        """
        pass

    def test_update_org_branding(self) -> None:
        """Test case for update_org_branding

        Update org branding
        """
        pass

    def test_upload_org_logo(self) -> None:
        """Test case for upload_org_logo

        Upload org logo
        """
        pass


if __name__ == '__main__':
    unittest.main()
