# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_api_tokens200_response import ListApiTokens200Response

class TestListApiTokens200Response(unittest.TestCase):
    """ListApiTokens200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListApiTokens200Response:
        """Test ListApiTokens200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListApiTokens200Response`
        """
        model = ListApiTokens200Response()
        if include_optional:
            return ListApiTokens200Response(
                data = [
                    zippendo.models.list_api_tokens_200_response_data_inner.listApiTokens_200_response_data_inner(
                        id = 'tok_6e2fa83ij9', 
                        name = 'Warehouse integration', 
                        token_prefix = 'zipp_live_8f', 
                        scopes = ["read:shipments","write:shipments"], 
                        last_used_at = '2026-06-22T14:30:00.000Z', 
                        expires_at = '2026-09-20T14:30:00.000Z', 
                        created_at = '2026-06-22T14:30:00.000Z', 
                        created_by = zippendo.models.list_api_tokens_200_response_data_inner_created_by.listApiTokens_200_response_data_inner_createdBy(
                            id = 'usr_9f3kd92ld0', 
                            name = 'Anna Jensen', 
                            email = 'anna@example.dk', ), )
                    ],
                total = 137,
                page = 1,
                limit = 20,
                total_pages = 7
            )
        else:
            return ListApiTokens200Response(
                data = [
                    zippendo.models.list_api_tokens_200_response_data_inner.listApiTokens_200_response_data_inner(
                        id = 'tok_6e2fa83ij9', 
                        name = 'Warehouse integration', 
                        token_prefix = 'zipp_live_8f', 
                        scopes = ["read:shipments","write:shipments"], 
                        last_used_at = '2026-06-22T14:30:00.000Z', 
                        expires_at = '2026-09-20T14:30:00.000Z', 
                        created_at = '2026-06-22T14:30:00.000Z', 
                        created_by = zippendo.models.list_api_tokens_200_response_data_inner_created_by.listApiTokens_200_response_data_inner_createdBy(
                            id = 'usr_9f3kd92ld0', 
                            name = 'Anna Jensen', 
                            email = 'anna@example.dk', ), )
                    ],
                total = 137,
                page = 1,
                limit = 20,
                total_pages = 7,
        )
        """

    def testListApiTokens200Response(self):
        """Test ListApiTokens200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
