# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.batch_send_shipments200_response import BatchSendShipments200Response

class TestBatchSendShipments200Response(unittest.TestCase):
    """BatchSendShipments200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchSendShipments200Response:
        """Test BatchSendShipments200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchSendShipments200Response`
        """
        model = BatchSendShipments200Response()
        if include_optional:
            return BatchSendShipments200Response(
                results = [
                    zippendo.models.batch_send_shipments_200_response_results_inner.batchSendShipments_200_response_results_inner(
                        shipment_id = 'shp_01H8XABC123', 
                        status = 'sent', 
                        code = 'CARRIER_ERROR', 
                        message = 'Shipment must be in pending or error status to be sent', 
                        errors = [
                            zippendo.models.send_shipment_422_response_errors_inner.sendShipment_422_response_errors_inner(
                                code = 'INVALID_POSTAL_CODE', 
                                message = 'Receiver postal code is invalid for the selected product.', )
                            ], )
                    ],
                summary = zippendo.models.batch_send_shipments_200_response_summary.batchSendShipments_200_response_summary(
                    total = 3, 
                    sent = 2, 
                    failed = 1, )
            )
        else:
            return BatchSendShipments200Response(
                results = [
                    zippendo.models.batch_send_shipments_200_response_results_inner.batchSendShipments_200_response_results_inner(
                        shipment_id = 'shp_01H8XABC123', 
                        status = 'sent', 
                        code = 'CARRIER_ERROR', 
                        message = 'Shipment must be in pending or error status to be sent', 
                        errors = [
                            zippendo.models.send_shipment_422_response_errors_inner.sendShipment_422_response_errors_inner(
                                code = 'INVALID_POSTAL_CODE', 
                                message = 'Receiver postal code is invalid for the selected product.', )
                            ], )
                    ],
                summary = zippendo.models.batch_send_shipments_200_response_summary.batchSendShipments_200_response_summary(
                    total = 3, 
                    sent = 2, 
                    failed = 1, ),
        )
        """

    def testBatchSendShipments200Response(self):
        """Test BatchSendShipments200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
