# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.api.carriers_api import CarriersApi


class TestCarriersApi(unittest.TestCase):
    """CarriersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CarriersApi()

    def tearDown(self) -> None:
        pass

    def test_connect_carrier(self) -> None:
        """Test case for connect_carrier

        Connect carrier
        """
        pass

    def test_disconnect_carrier(self) -> None:
        """Test case for disconnect_carrier

        Disconnect carrier
        """
        pass

    def test_get_carrier(self) -> None:
        """Test case for get_carrier

        Get carrier
        """
        pass

    def test_list_carrier_product_service_points(self) -> None:
        """Test case for list_carrier_product_service_points

        List product service points
        """
        pass

    def test_list_carrier_products(self) -> None:
        """Test case for list_carrier_products

        List carrier products
        """
        pass

    def test_list_carriers(self) -> None:
        """Test case for list_carriers

        List carriers
        """
        pass

    def test_update_carrier(self) -> None:
        """Test case for update_carrier

        Update carrier
        """
        pass


if __name__ == '__main__':
    unittest.main()
