# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_order201_response import CreateOrder201Response

class TestCreateOrder201Response(unittest.TestCase):
    """CreateOrder201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrder201Response:
        """Test CreateOrder201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrder201Response`
        """
        model = CreateOrder201Response()
        if include_optional:
            return CreateOrder201Response(
                id = 'clz9k2f0a0003abcd9012mnop',
                order_number = '#1042',
                external_id = '5012345678901',
                customer_name = 'Anna Jensen',
                customer_email = 'anna@example.dk',
                shipping_address = zippendo.models.create_order_201_response_shipping_address.createOrder_201_response_shippingAddress(
                    name = 'Anna Jensen', 
                    attention = 'c/o Reception', 
                    company = 'Jensen Design ApS', 
                    address1 = 'Nørregade 12', 
                    address2 = '2. sal', 
                    city = 'København', 
                    province = 'Hovedstaden', 
                    province_code = 'DK-84', 
                    postal_code = '1165', 
                    country = 'Denmark', 
                    country_code = 'DK', 
                    phone = '+45 12 34 56 78', 
                    email = 'anna@example.dk', ),
                order_lines = [
                    zippendo.models.create_order_201_response_order_lines_inner.createOrder_201_response_orderLines_inner(
                        sku = 'SKU-1042-BLK', 
                        name = 'Wool Sweater', 
                        quantity = 2, 
                        unit_price = 499, 
                        total_price = 998, 
                        currency = 'DKK', 
                        weight = 0.5, 
                        weight_unit = 'kg', 
                        variant_id = '44218900291', 
                        product_id = '8123456789', 
                        image_url = 'https://cdn.example.dk/products/sweater.jpg', 
                        hs_code = '611020', 
                        country_of_origin = 'DK', 
                        province_of_origin = 'DK-84', 
                        barcode = '5712345678901', 
                        requires_shipping = True, 
                        taxable = True, 
                        gift_card = False, 
                        vendor = 'Norse Knits', )
                    ],
                subtotal_amount = 998,
                total_amount = 1047,
                currency = 'DKK',
                status = 'processing',
                shipping_rule_id = 'clz9k2f0a0002abcd5678ijkl',
                notes = 'Leave at front desk',
                external_data = {
                    'key' : null
                    },
                order_channel_id = 'clz9k2f0a0001abcd1234efgh',
                org_id = 'clz9k2f0a0000abcd0000zzzz',
                created_at = '2026-06-22T14:30:00.000Z',
                updated_at = '2026-06-22T14:30:00.000Z'
            )
        else:
            return CreateOrder201Response(
                id = 'clz9k2f0a0003abcd9012mnop',
                order_number = '#1042',
                order_lines = [
                    zippendo.models.create_order_201_response_order_lines_inner.createOrder_201_response_orderLines_inner(
                        sku = 'SKU-1042-BLK', 
                        name = 'Wool Sweater', 
                        quantity = 2, 
                        unit_price = 499, 
                        total_price = 998, 
                        currency = 'DKK', 
                        weight = 0.5, 
                        weight_unit = 'kg', 
                        variant_id = '44218900291', 
                        product_id = '8123456789', 
                        image_url = 'https://cdn.example.dk/products/sweater.jpg', 
                        hs_code = '611020', 
                        country_of_origin = 'DK', 
                        province_of_origin = 'DK-84', 
                        barcode = '5712345678901', 
                        requires_shipping = True, 
                        taxable = True, 
                        gift_card = False, 
                        vendor = 'Norse Knits', )
                    ],
                status = 'processing',
                order_channel_id = 'clz9k2f0a0001abcd1234efgh',
                org_id = 'clz9k2f0a0000abcd0000zzzz',
                created_at = '2026-06-22T14:30:00.000Z',
                updated_at = '2026-06-22T14:30:00.000Z',
        )
        """

    def testCreateOrder201Response(self):
        """Test CreateOrder201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
