# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_api_token201_response import CreateApiToken201Response

class TestCreateApiToken201Response(unittest.TestCase):
    """CreateApiToken201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApiToken201Response:
        """Test CreateApiToken201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApiToken201Response`
        """
        model = CreateApiToken201Response()
        if include_optional:
            return CreateApiToken201Response(
                id = 'tok_6e2fa83ij9',
                name = 'Warehouse integration',
                token_prefix = 'zipp_live_8f',
                scopes = ["read:shipments","write:shipments"],
                brand_id = 'brnd_8f3kd92ld0',
                last_used_at = '2026-06-22T14:30:00.000Z',
                expires_at = '2026-09-20T14:30:00.000Z',
                created_at = '2026-06-22T14:30:00.000Z',
                token = 'zipp_live_8f3kd92ld0a7b6c5d4e3f2a1'
            )
        else:
            return CreateApiToken201Response(
                id = 'tok_6e2fa83ij9',
                name = 'Warehouse integration',
                token_prefix = 'zipp_live_8f',
                scopes = ["read:shipments","write:shipments"],
                brand_id = 'brnd_8f3kd92ld0',
                last_used_at = '2026-06-22T14:30:00.000Z',
                expires_at = '2026-09-20T14:30:00.000Z',
                created_at = '2026-06-22T14:30:00.000Z',
                token = 'zipp_live_8f3kd92ld0a7b6c5d4e3f2a1',
        )
        """

    def testCreateApiToken201Response(self):
        """Test CreateApiToken201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
