# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.get_order200_response_shipments_inner import GetOrder200ResponseShipmentsInner

class TestGetOrder200ResponseShipmentsInner(unittest.TestCase):
    """GetOrder200ResponseShipmentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrder200ResponseShipmentsInner:
        """Test GetOrder200ResponseShipmentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrder200ResponseShipmentsInner`
        """
        model = GetOrder200ResponseShipmentsInner()
        if include_optional:
            return GetOrder200ResponseShipmentsInner(
                id = 'shp_4d9e7a2f',
                reference = 'ORDER-1042',
                status = 'pending',
                type = 'outbound',
                tracking = zippendo.models.create_shipment_201_response_tracking.createShipment_201_response_tracking(
                    url = 'https://tracking.postnord.com/00370724710000012345', 
                    number = '00370724710000012345', 
                    label_free_code = 'AB12CD34', 
                    qr_code_link = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 
                    qr_code_data_uri = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 
                    qr_code_url = 'https://qr.bring.com/label-free/AB12CD34.png', ),
                carrier_settings = zippendo.models.list_shipments_200_response_data_inner_carrier_settings.listShipments_200_response_data_inner_carrierSettings(
                    carrier_id = 'car_pn_001', 
                    product_id = 'prod_mypack_home', 
                    services = ["A7"], 
                    additional_parameters = {"notificationEmail":"anna@example.dk"}, ),
                created_at = '2026-06-22T14:30:00.000Z',
                updated_at = '2026-06-22T14:30:00.000Z',
                shipping_rule_id = 'clz9k2f0a0002abcd5678ijkl',
                documents = [
                    zippendo.models.create_shipment_201_response_documents_inner.createShipment_201_response_documents_inner(
                        id = 'doc_8f3a2b1c', 
                        shipment_id = 'shp_4d9e7a2f', 
                        document_type = 'label', 
                        format = 'pdf', 
                        content = 'JVBERi0xLjQKJeLjz9MKMS...', 
                        size = 'A4', 
                        created_at = '2026-06-22T14:30:00.000Z', 
                        updated_at = '2026-06-22T14:30:00.000Z', )
                    ]
            )
        else:
            return GetOrder200ResponseShipmentsInner(
                id = 'shp_4d9e7a2f',
                reference = 'ORDER-1042',
                status = 'pending',
                type = 'outbound',
                carrier_settings = zippendo.models.list_shipments_200_response_data_inner_carrier_settings.listShipments_200_response_data_inner_carrierSettings(
                    carrier_id = 'car_pn_001', 
                    product_id = 'prod_mypack_home', 
                    services = ["A7"], 
                    additional_parameters = {"notificationEmail":"anna@example.dk"}, ),
                created_at = '2026-06-22T14:30:00.000Z',
                updated_at = '2026-06-22T14:30:00.000Z',
        )
        """

    def testGetOrder200ResponseShipmentsInner(self):
        """Test GetOrder200ResponseShipmentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
