# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipping_quote200_response_rates_inner import CreateShippingQuote200ResponseRatesInner

class TestCreateShippingQuote200ResponseRatesInner(unittest.TestCase):
    """CreateShippingQuote200ResponseRatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShippingQuote200ResponseRatesInner:
        """Test CreateShippingQuote200ResponseRatesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShippingQuote200ResponseRatesInner`
        """
        model = CreateShippingQuote200ResponseRatesInner()
        if include_optional:
            return CreateShippingQuote200ResponseRatesInner(
                service_name = 'Standard DK',
                service_code = 'postnord:PNL13:rule_01HZX9K2QF',
                total_price = '3900',
                currency = 'DKK',
                description = 'Standard levering i Danmark',
                min_delivery_date = '2026-06-24',
                max_delivery_date = '2026-06-26',
                carrier_name = 'PostNord',
                carrier_slug = 'postnord',
                product_id = 'PNL13',
                shipping_rule_id = 'rule_01HZX9K2QF'
            )
        else:
            return CreateShippingQuote200ResponseRatesInner(
                service_name = 'Standard DK',
                service_code = 'postnord:PNL13:rule_01HZX9K2QF',
                total_price = '3900',
                currency = 'DKK',
                shipping_rule_id = 'rule_01HZX9K2QF',
        )
        """

    def testCreateShippingQuote200ResponseRatesInner(self):
        """Test CreateShippingQuote200ResponseRatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
