# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipment201_response_logs_inner import CreateShipment201ResponseLogsInner

class TestCreateShipment201ResponseLogsInner(unittest.TestCase):
    """CreateShipment201ResponseLogsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShipment201ResponseLogsInner:
        """Test CreateShipment201ResponseLogsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShipment201ResponseLogsInner`
        """
        model = CreateShipment201ResponseLogsInner()
        if include_optional:
            return CreateShipment201ResponseLogsInner(
                id = 'log_6f7a8b9c',
                direction = 'outbound',
                request = None,
                response = None,
                status_code = 200,
                error = 'Connection timed out',
                duration = 342,
                created_at = '2026-06-22T14:30:00.000Z'
            )
        else:
            return CreateShipment201ResponseLogsInner(
                id = 'log_6f7a8b9c',
                direction = 'outbound',
                request = None,
                created_at = '2026-06-22T14:30:00.000Z',
        )
        """

    def testCreateShipment201ResponseLogsInner(self):
        """Test CreateShipment201ResponseLogsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
