# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.get_order200_response_shipping_rule import GetOrder200ResponseShippingRule

class TestGetOrder200ResponseShippingRule(unittest.TestCase):
    """GetOrder200ResponseShippingRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrder200ResponseShippingRule:
        """Test GetOrder200ResponseShippingRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrder200ResponseShippingRule`
        """
        model = GetOrder200ResponseShippingRule()
        if include_optional:
            return GetOrder200ResponseShippingRule(
                id = 'rule_3c4d5e6f',
                name = 'Domestic standard',
                carrier_id = 'car_pn_001',
                product_id = 'prod_mypack_home',
                services = ["A7"],
                address_id = 'addr_7e8f9a0b',
                return_shipping_rule_id = 'clz9k2f0a0004abcd3456qrst',
                auto_create_return_shipment = False,
                auto_print_labels = True,
                auto_print_documents = False,
                label_printer_id = 'prn_label_01',
                document_printer_id = 'prn_doc_01'
            )
        else:
            return GetOrder200ResponseShippingRule(
                id = 'rule_3c4d5e6f',
                name = 'Domestic standard',
                carrier_id = 'car_pn_001',
                product_id = 'prod_mypack_home',
                services = ["A7"],
                address_id = 'addr_7e8f9a0b',
        )
        """

    def testGetOrder200ResponseShippingRule(self):
        """Test GetOrder200ResponseShippingRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
