# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.verify_api_token200_response import VerifyApiToken200Response

class TestVerifyApiToken200Response(unittest.TestCase):
    """VerifyApiToken200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyApiToken200Response:
        """Test VerifyApiToken200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyApiToken200Response`
        """
        model = VerifyApiToken200Response()
        if include_optional:
            return VerifyApiToken200Response(
                valid = True,
                token_id = 'tok_6e2fa83ij9',
                user_id = 'usr_9f3kd92ld0',
                org_id = 'org_4d8af01qw2',
                scopes = ["read:shipments"],
                expires_at = '2026-09-20T14:30:00.000Z'
            )
        else:
            return VerifyApiToken200Response(
                valid = True,
        )
        """

    def testVerifyApiToken200Response(self):
        """Test VerifyApiToken200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
