# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.update_api_token_request import UpdateApiTokenRequest

class TestUpdateApiTokenRequest(unittest.TestCase):
    """UpdateApiTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateApiTokenRequest:
        """Test UpdateApiTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateApiTokenRequest`
        """
        model = UpdateApiTokenRequest()
        if include_optional:
            return UpdateApiTokenRequest(
                name = 'Warehouse integration'
            )
        else:
            return UpdateApiTokenRequest(
                name = 'Warehouse integration',
        )
        """

    def testUpdateApiTokenRequest(self):
        """Test UpdateApiTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
