# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_addresses200_response_data_inner import ListAddresses200ResponseDataInner

class TestListAddresses200ResponseDataInner(unittest.TestCase):
    """ListAddresses200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAddresses200ResponseDataInner:
        """Test ListAddresses200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAddresses200ResponseDataInner`
        """
        model = ListAddresses200ResponseDataInner()
        if include_optional:
            return ListAddresses200ResponseDataInner(
                id = 'addr_01HZX9K2QF',
                name = 'Hovedlager',
                att_contact = 'Mette Hansen',
                address1 = 'Vesterbrogade 1',
                address2 = '2. sal',
                zipcode = '1620',
                city = 'København',
                phone = '+4533123456',
                country_code = 'DK',
                state = '',
                email = 'lager@example.dk',
                customs = {"eori":"DK12345678"},
                address_types = ["sender"],
                org_id = 'org_01HZX9K2QF',
                created_at = '2026-06-22T09:00:00.000Z',
                updated_at = '2026-06-22T09:00:00.000Z'
            )
        else:
            return ListAddresses200ResponseDataInner(
                id = 'addr_01HZX9K2QF',
                name = 'Hovedlager',
                att_contact = 'Mette Hansen',
                address1 = 'Vesterbrogade 1',
                address2 = '2. sal',
                zipcode = '1620',
                city = 'København',
                phone = '+4533123456',
                country_code = 'DK',
                state = '',
                email = 'lager@example.dk',
                address_types = ["sender"],
                org_id = 'org_01HZX9K2QF',
                created_at = '2026-06-22T09:00:00.000Z',
                updated_at = '2026-06-22T09:00:00.000Z',
        )
        """

    def testListAddresses200ResponseDataInner(self):
        """Test ListAddresses200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
