# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.get_billing_usage200_response_limits import GetBillingUsage200ResponseLimits

class TestGetBillingUsage200ResponseLimits(unittest.TestCase):
    """GetBillingUsage200ResponseLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingUsage200ResponseLimits:
        """Test GetBillingUsage200ResponseLimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBillingUsage200ResponseLimits`
        """
        model = GetBillingUsage200ResponseLimits()
        if include_optional:
            return GetBillingUsage200ResponseLimits(
                team_members = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                carriers = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                order_channels = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                shipping_rules = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                addresses = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                api_tokens = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                automations = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, )
            )
        else:
            return GetBillingUsage200ResponseLimits(
                team_members = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                carriers = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                order_channels = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                shipping_rules = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                addresses = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                api_tokens = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
                automations = zippendo.models.get_billing_usage_200_response_limits_team_members.getBillingUsage_200_response_limits_teamMembers(
                    used = 3, 
                    limit = 5, ),
        )
        """

    def testGetBillingUsage200ResponseLimits(self):
        """Test GetBillingUsage200ResponseLimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
