# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_order201_response_order_lines_inner import CreateOrder201ResponseOrderLinesInner

class TestCreateOrder201ResponseOrderLinesInner(unittest.TestCase):
    """CreateOrder201ResponseOrderLinesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrder201ResponseOrderLinesInner:
        """Test CreateOrder201ResponseOrderLinesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrder201ResponseOrderLinesInner`
        """
        model = CreateOrder201ResponseOrderLinesInner()
        if include_optional:
            return CreateOrder201ResponseOrderLinesInner(
                sku = 'SKU-1042-BLK',
                name = 'Wool Sweater',
                quantity = 2,
                unit_price = 499,
                total_price = 998,
                currency = 'DKK',
                weight = 0.5,
                weight_unit = 'kg',
                variant_id = '44218900291',
                product_id = '8123456789',
                image_url = 'https://cdn.example.dk/products/sweater.jpg',
                hs_code = '611020',
                country_of_origin = 'DK',
                province_of_origin = 'DK-84',
                barcode = '5712345678901',
                requires_shipping = True,
                taxable = True,
                gift_card = False,
                vendor = 'Norse Knits'
            )
        else:
            return CreateOrder201ResponseOrderLinesInner(
                name = 'Wool Sweater',
                quantity = 2,
        )
        """

    def testCreateOrder201ResponseOrderLinesInner(self):
        """Test CreateOrder201ResponseOrderLinesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
