# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_api_token201_response import CreateApiToken201Response

class TestCreateApiToken201Response(unittest.TestCase):
    """CreateApiToken201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApiToken201Response:
        """Test CreateApiToken201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApiToken201Response`
        """
        model = CreateApiToken201Response()
        if include_optional:
            return CreateApiToken201Response(
                id = 'tok_6e2fa83ij9',
                name = 'Warehouse integration',
                token_prefix = 'zipp_live_8f',
                scopes = ["read:shipments","write:shipments"],
                last_used_at = '2026-06-22T14:30:00.000Z',
                expires_at = '2026-09-20T14:30:00.000Z',
                created_at = '2026-06-22T14:30:00.000Z',
                token = 'zipp_live_8f3kd92ld0a7b6c5d4e3f2a1'
            )
        else:
            return CreateApiToken201Response(
                id = 'tok_6e2fa83ij9',
                name = 'Warehouse integration',
                token_prefix = 'zipp_live_8f',
                scopes = ["read:shipments","write:shipments"],
                last_used_at = '2026-06-22T14:30:00.000Z',
                expires_at = '2026-09-20T14:30:00.000Z',
                created_at = '2026-06-22T14:30:00.000Z',
                token = 'zipp_live_8f3kd92ld0a7b6c5d4e3f2a1',
        )
        """

    def testCreateApiToken201Response(self):
        """Test CreateApiToken201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
