# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_address_request import CreateAddressRequest

class TestCreateAddressRequest(unittest.TestCase):
    """CreateAddressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAddressRequest:
        """Test CreateAddressRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAddressRequest`
        """
        model = CreateAddressRequest()
        if include_optional:
            return CreateAddressRequest(
                name = 'Hovedlager',
                att_contact = 'Mette Hansen',
                address1 = 'Vesterbrogade 1',
                address2 = '2. sal',
                zipcode = '1620',
                city = 'København',
                phone = '+4533123456',
                country_code = 'DK',
                state = '',
                email = 'lager@example.dk',
                customs = {"eori":"DK12345678"},
                address_types = ["sender"]
            )
        else:
            return CreateAddressRequest(
                name = 'Hovedlager',
                att_contact = 'Mette Hansen',
                address1 = 'Vesterbrogade 1',
                zipcode = '1620',
                city = 'København',
                phone = '+4533123456',
                country_code = 'DK',
                email = 'lager@example.dk',
        )
        """

    def testCreateAddressRequest(self):
        """Test CreateAddressRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
