# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.update_org_request import UpdateOrgRequest

class TestUpdateOrgRequest(unittest.TestCase):
    """UpdateOrgRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrgRequest:
        """Test UpdateOrgRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrgRequest`
        """
        model = UpdateOrgRequest()
        if include_optional:
            return UpdateOrgRequest(
                name = 'Nordic Logistics ApS',
                slug = 'nordic-logistics',
                description = 'Parcel and freight logistics across the Nordics',
                currency = 'DKK',
                vat_number = 'DK12345678',
                overage_enabled = False,
                billing_email = 'billing@nordic-logistics.dk',
                company_name = 'Nordic Logistics ApS',
                address_line1 = 'Havnegade 12',
                address_line2 = '3. sal',
                city = 'København',
                postal_code = '1058',
                country = 'DK',
                customs = {
                    'key' : ''
                    }
            )
        else:
            return UpdateOrgRequest(
        )
        """

    def testUpdateOrgRequest(self):
        """Test UpdateOrgRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
