# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipment_request_carrier_settings import CreateShipmentRequestCarrierSettings

class TestCreateShipmentRequestCarrierSettings(unittest.TestCase):
    """CreateShipmentRequestCarrierSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShipmentRequestCarrierSettings:
        """Test CreateShipmentRequestCarrierSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShipmentRequestCarrierSettings`
        """
        model = CreateShipmentRequestCarrierSettings()
        if include_optional:
            return CreateShipmentRequestCarrierSettings(
                carrier_id = 'car_pn_001',
                product_id = 'prod_mypack_home',
                services = ["A7"],
                additional_parameters = {"notificationEmail":"anna@example.dk"}
            )
        else:
            return CreateShipmentRequestCarrierSettings(
                carrier_id = 'car_pn_001',
                product_id = 'prod_mypack_home',
                services = ["A7"],
                additional_parameters = {"notificationEmail":"anna@example.dk"},
        )
        """

    def testCreateShipmentRequestCarrierSettings(self):
        """Test CreateShipmentRequestCarrierSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
