# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_shipping_rules200_response_data_inner import ListShippingRules200ResponseDataInner

class TestListShippingRules200ResponseDataInner(unittest.TestCase):
    """ListShippingRules200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListShippingRules200ResponseDataInner:
        """Test ListShippingRules200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListShippingRules200ResponseDataInner`
        """
        model = ListShippingRules200ResponseDataInner()
        if include_optional:
            return ListShippingRules200ResponseDataInner(
                id = 'rule_01HZX9K2QF',
                name = 'Standard DK',
                description = 'Standard levering i Danmark',
                direction = 'outbound',
                carrier_id = 'carr_01HZX9K2QF',
                product_id = 'PNL13',
                services = ["EMAIL_NOTIFICATION"],
                additional_parameters = [{"name":"returnFunctionality","val":"LABELLESS"}],
                address_id = 'addr_01HZX9K2QF',
                receiving_countries = ["DK","SE"],
                email_notification = True,
                phone_notification = False,
                min_weight = 0,
                max_weight = 20,
                min_order_value = 0,
                max_order_value = 5000,
                conditions = [{"type":"flatRate","shippingPrice":39,"currency":"DKK"}],
                generate_proforma_invoice = False,
                generate_commercial_invoice = False,
                generate_packing_list = False,
                auto_print_labels = False,
                auto_print_documents = False,
                label_printer_id = '',
                document_printer_id = '',
                return_shipping_rule_id = '',
                auto_create_return_shipment = False,
                org_id = 'org_01HZX9K2QF',
                created_at = '2026-06-22T09:00:00.000Z',
                updated_at = '2026-06-22T09:00:00.000Z',
                carrier = zippendo.models.list_shipping_rules_200_response_data_inner_carrier.listShippingRules_200_response_data_inner_carrier(
                    id = 'carr_01HZX9K2QF', 
                    name = 'PostNord', 
                    carrier_slug = 'postnord', 
                    config = {"customerNumber":"123456"}, 
                    org_id = 'org_01HZX9K2QF', 
                    created_at = '2026-06-22T09:00:00.000Z', 
                    updated_at = '2026-06-22T09:00:00.000Z', ),
                address = zippendo.models.list_addresses_200_response_data_inner.listAddresses_200_response_data_inner(
                    id = 'addr_01HZX9K2QF', 
                    name = 'Hovedlager', 
                    att_contact = 'Mette Hansen', 
                    address1 = 'Vesterbrogade 1', 
                    address2 = '2. sal', 
                    zipcode = '1620', 
                    city = 'København', 
                    phone = '+4533123456', 
                    country_code = 'DK', 
                    state = '', 
                    email = 'lager@example.dk', 
                    customs = {"eori":"DK12345678"}, 
                    address_types = ["sender"], 
                    org_id = 'org_01HZX9K2QF', 
                    created_at = '2026-06-22T09:00:00.000Z', 
                    updated_at = '2026-06-22T09:00:00.000Z', ),
                label_printer = zippendo.models.list_shipping_rules_200_response_data_inner_label_printer.listShippingRules_200_response_data_inner_labelPrinter(
                    id = 'prn_01HZX9K2QF', 
                    name = 'Zebra ZD420 Lager', ),
                document_printer = zippendo.models.list_shipping_rules_200_response_data_inner_label_printer.listShippingRules_200_response_data_inner_labelPrinter(
                    id = 'prn_01HZX9K2QF', 
                    name = 'Zebra ZD420 Lager', ),
                return_shipping_rule = zippendo.models.list_shipping_rules_200_response_data_inner_return_shipping_rule.listShippingRules_200_response_data_inner_returnShippingRule(
                    id = 'rule_01HZX9K2QF', 
                    name = 'Retur DK', )
            )
        else:
            return ListShippingRules200ResponseDataInner(
                id = 'rule_01HZX9K2QF',
                name = 'Standard DK',
                description = 'Standard levering i Danmark',
                direction = 'outbound',
                carrier_id = 'carr_01HZX9K2QF',
                product_id = 'PNL13',
                services = ["EMAIL_NOTIFICATION"],
                additional_parameters = [{"name":"returnFunctionality","val":"LABELLESS"}],
                address_id = 'addr_01HZX9K2QF',
                receiving_countries = ["DK","SE"],
                email_notification = True,
                phone_notification = False,
                min_weight = 0,
                max_weight = 20,
                min_order_value = 0,
                max_order_value = 5000,
                conditions = [{"type":"flatRate","shippingPrice":39,"currency":"DKK"}],
                generate_proforma_invoice = False,
                generate_commercial_invoice = False,
                generate_packing_list = False,
                auto_print_labels = False,
                auto_print_documents = False,
                label_printer_id = '',
                document_printer_id = '',
                return_shipping_rule_id = '',
                auto_create_return_shipment = False,
                org_id = 'org_01HZX9K2QF',
                created_at = '2026-06-22T09:00:00.000Z',
                updated_at = '2026-06-22T09:00:00.000Z',
                carrier = zippendo.models.list_shipping_rules_200_response_data_inner_carrier.listShippingRules_200_response_data_inner_carrier(
                    id = 'carr_01HZX9K2QF', 
                    name = 'PostNord', 
                    carrier_slug = 'postnord', 
                    config = {"customerNumber":"123456"}, 
                    org_id = 'org_01HZX9K2QF', 
                    created_at = '2026-06-22T09:00:00.000Z', 
                    updated_at = '2026-06-22T09:00:00.000Z', ),
                address = zippendo.models.list_addresses_200_response_data_inner.listAddresses_200_response_data_inner(
                    id = 'addr_01HZX9K2QF', 
                    name = 'Hovedlager', 
                    att_contact = 'Mette Hansen', 
                    address1 = 'Vesterbrogade 1', 
                    address2 = '2. sal', 
                    zipcode = '1620', 
                    city = 'København', 
                    phone = '+4533123456', 
                    country_code = 'DK', 
                    state = '', 
                    email = 'lager@example.dk', 
                    customs = {"eori":"DK12345678"}, 
                    address_types = ["sender"], 
                    org_id = 'org_01HZX9K2QF', 
                    created_at = '2026-06-22T09:00:00.000Z', 
                    updated_at = '2026-06-22T09:00:00.000Z', ),
        )
        """

    def testListShippingRules200ResponseDataInner(self):
        """Test ListShippingRules200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
