# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_org_webhook201_response import CreateOrgWebhook201Response

class TestCreateOrgWebhook201Response(unittest.TestCase):
    """CreateOrgWebhook201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrgWebhook201Response:
        """Test CreateOrgWebhook201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrgWebhook201Response`
        """
        model = CreateOrgWebhook201Response()
        if include_optional:
            return CreateOrgWebhook201Response(
                id = 'wh_clx1a2b3c4',
                name = 'Order fulfilment notifier',
                url = 'https://hooks.example.dk/zippendo',
                secret = 'whsec_8f3a1c2b9d4e5f6a',
                events = ["shipment.created"],
                is_active = True,
                created_at = '2026-06-01T09:30:00.000Z',
                updated_at = '2026-06-10T11:15:00.000Z'
            )
        else:
            return CreateOrgWebhook201Response(
                id = 'wh_clx1a2b3c4',
                name = 'Order fulfilment notifier',
                url = 'https://hooks.example.dk/zippendo',
                secret = 'whsec_8f3a1c2b9d4e5f6a',
                events = ["shipment.created"],
                is_active = True,
                created_at = '2026-06-01T09:30:00.000Z',
                updated_at = '2026-06-10T11:15:00.000Z',
        )
        """

    def testCreateOrgWebhook201Response(self):
        """Test CreateOrgWebhook201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
