# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_available_carriers200_response_inner_required_fields_inner import ListAvailableCarriers200ResponseInnerRequiredFieldsInner

class TestListAvailableCarriers200ResponseInnerRequiredFieldsInner(unittest.TestCase):
    """ListAvailableCarriers200ResponseInnerRequiredFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAvailableCarriers200ResponseInnerRequiredFieldsInner:
        """Test ListAvailableCarriers200ResponseInnerRequiredFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAvailableCarriers200ResponseInnerRequiredFieldsInner`
        """
        model = ListAvailableCarriers200ResponseInnerRequiredFieldsInner()
        if include_optional:
            return ListAvailableCarriers200ResponseInnerRequiredFieldsInner(
                name = 'Customer number',
                key = 'customerNumber',
                type = 'string',
                options = [
                    zippendo.models.list_carrier_products_200_response_inner_additional_parameters_inner_options_inner.listCarrierProducts_200_response_inner_additionalParameters_inner_options_inner(
                        name = 'Standard', 
                        key = 'standard', 
                        value = 'STD', )
                    ],
                description = 'Your PostNord customer number',
                required = True
            )
        else:
            return ListAvailableCarriers200ResponseInnerRequiredFieldsInner(
                name = 'Customer number',
                key = 'customerNumber',
                type = 'string',
                description = 'Your PostNord customer number',
        )
        """

    def testListAvailableCarriers200ResponseInnerRequiredFieldsInner(self):
        """Test ListAvailableCarriers200ResponseInnerRequiredFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
