# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.get_billing_usage200_response_shipments import GetBillingUsage200ResponseShipments

class TestGetBillingUsage200ResponseShipments(unittest.TestCase):
    """GetBillingUsage200ResponseShipments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingUsage200ResponseShipments:
        """Test GetBillingUsage200ResponseShipments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBillingUsage200ResponseShipments`
        """
        model = GetBillingUsage200ResponseShipments()
        if include_optional:
            return GetBillingUsage200ResponseShipments(
                used = 1240,
                included = 1000,
                overage = 240,
                overage_charges = 36000
            )
        else:
            return GetBillingUsage200ResponseShipments(
                used = 1240,
                included = 1000,
                overage = 240,
                overage_charges = 36000,
        )
        """

    def testGetBillingUsage200ResponseShipments(self):
        """Test GetBillingUsage200ResponseShipments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
