# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.verify_api_token_request import VerifyApiTokenRequest

class TestVerifyApiTokenRequest(unittest.TestCase):
    """VerifyApiTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyApiTokenRequest:
        """Test VerifyApiTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyApiTokenRequest`
        """
        model = VerifyApiTokenRequest()
        if include_optional:
            return VerifyApiTokenRequest(
                token = 'zipp_live_8f3kd92ld0a7b6c5d4e3f2a1'
            )
        else:
            return VerifyApiTokenRequest(
                token = 'zipp_live_8f3kd92ld0a7b6c5d4e3f2a1',
        )
        """

    def testVerifyApiTokenRequest(self):
        """Test VerifyApiTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
