# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.send_shipment422_response_errors_inner import SendShipment422ResponseErrorsInner

class TestSendShipment422ResponseErrorsInner(unittest.TestCase):
    """SendShipment422ResponseErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendShipment422ResponseErrorsInner:
        """Test SendShipment422ResponseErrorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendShipment422ResponseErrorsInner`
        """
        model = SendShipment422ResponseErrorsInner()
        if include_optional:
            return SendShipment422ResponseErrorsInner(
                code = 'INVALID_POSTAL_CODE',
                message = 'Receiver postal code is invalid for the selected product.'
            )
        else:
            return SendShipment422ResponseErrorsInner(
                message = 'Receiver postal code is invalid for the selected product.',
        )
        """

    def testSendShipment422ResponseErrorsInner(self):
        """Test SendShipment422ResponseErrorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
