# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipping_rule_request_additional_parameters_any_of_value import CreateShippingRuleRequestAdditionalParametersAnyOfValue

class TestCreateShippingRuleRequestAdditionalParametersAnyOfValue(unittest.TestCase):
    """CreateShippingRuleRequestAdditionalParametersAnyOfValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShippingRuleRequestAdditionalParametersAnyOfValue:
        """Test CreateShippingRuleRequestAdditionalParametersAnyOfValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShippingRuleRequestAdditionalParametersAnyOfValue`
        """
        model = CreateShippingRuleRequestAdditionalParametersAnyOfValue()
        if include_optional:
            return CreateShippingRuleRequestAdditionalParametersAnyOfValue(
                id = 'sp_pn_4521',
                name = 'Føtex Nørrebro',
                address = 'Nørrebrogade 20, 2200 København N',
                coordinates = [55.6987, 12.5501]
            )
        else:
            return CreateShippingRuleRequestAdditionalParametersAnyOfValue(
                id = 'sp_pn_4521',
                name = 'Føtex Nørrebro',
                address = 'Nørrebrogade 20, 2200 København N',
        )
        """

    def testCreateShippingRuleRequestAdditionalParametersAnyOfValue(self):
        """Test CreateShippingRuleRequestAdditionalParametersAnyOfValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
