# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_shipping_rules200_response_data_inner_conditions_inner_one_of1 import ListShippingRules200ResponseDataInnerConditionsInnerOneOf1

class TestListShippingRules200ResponseDataInnerConditionsInnerOneOf1(unittest.TestCase):
    """ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListShippingRules200ResponseDataInnerConditionsInnerOneOf1:
        """Test ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListShippingRules200ResponseDataInnerConditionsInnerOneOf1`
        """
        model = ListShippingRules200ResponseDataInnerConditionsInnerOneOf1()
        if include_optional:
            return ListShippingRules200ResponseDataInnerConditionsInnerOneOf1(
                type = 'price',
                price_type = 'total',
                operator = 'gte',
                value = 500,
                shipping_price = 0,
                currency = 'DKK'
            )
        else:
            return ListShippingRules200ResponseDataInnerConditionsInnerOneOf1(
                type = 'price',
                price_type = 'total',
                operator = 'gte',
                value = 500,
                shipping_price = 0,
                currency = 'DKK',
        )
        """

    def testListShippingRules200ResponseDataInnerConditionsInnerOneOf1(self):
        """Test ListShippingRules200ResponseDataInnerConditionsInnerOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
