# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_carriers200_response import ListCarriers200Response

class TestListCarriers200Response(unittest.TestCase):
    """ListCarriers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCarriers200Response:
        """Test ListCarriers200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCarriers200Response`
        """
        model = ListCarriers200Response()
        if include_optional:
            return ListCarriers200Response(
                data = [
                    zippendo.models.list_carriers_200_response_data_inner.listCarriers_200_response_data_inner(
                        id = 'carr_01HZX9K2QF', 
                        name = 'PostNord', 
                        carrier_slug = 'postnord', 
                        config = {"customerNumber":"123456"}, 
                        org_id = 'org_01HZX9K2QF', 
                        created_at = '2026-06-22T09:00:00.000Z', 
                        updated_at = '2026-06-22T09:00:00.000Z', 
                        logo = 'https://cdn.zippendo.com/logos/postnord.svg', 
                        brand_color = '#005BAA', 
                        deprecated = True, 
                        deprecation_message = 'The standalone Instabox API is deprecated. Migrate to the Instabee-powered Instabox integration.', )
                    ],
                total = 137,
                page = 1,
                limit = 20,
                total_pages = 7
            )
        else:
            return ListCarriers200Response(
                data = [
                    zippendo.models.list_carriers_200_response_data_inner.listCarriers_200_response_data_inner(
                        id = 'carr_01HZX9K2QF', 
                        name = 'PostNord', 
                        carrier_slug = 'postnord', 
                        config = {"customerNumber":"123456"}, 
                        org_id = 'org_01HZX9K2QF', 
                        created_at = '2026-06-22T09:00:00.000Z', 
                        updated_at = '2026-06-22T09:00:00.000Z', 
                        logo = 'https://cdn.zippendo.com/logos/postnord.svg', 
                        brand_color = '#005BAA', 
                        deprecated = True, 
                        deprecation_message = 'The standalone Instabox API is deprecated. Migrate to the Instabee-powered Instabox integration.', )
                    ],
                total = 137,
                page = 1,
                limit = 20,
                total_pages = 7,
        )
        """

    def testListCarriers200Response(self):
        """Test ListCarriers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
