# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_org_webhook(self) -> None:
        """Test case for create_org_webhook

        Create webhook
        """
        pass

    def test_delete_org_webhook(self) -> None:
        """Test case for delete_org_webhook

        Delete webhook
        """
        pass

    def test_get_org_webhook(self) -> None:
        """Test case for get_org_webhook

        Get webhook
        """
        pass

    def test_list_org_webhook_deliveries(self) -> None:
        """Test case for list_org_webhook_deliveries

        List webhook deliveries
        """
        pass

    def test_list_org_webhooks(self) -> None:
        """Test case for list_org_webhooks

        List webhooks
        """
        pass

    def test_test_org_webhook(self) -> None:
        """Test case for test_org_webhook

        Test webhook
        """
        pass

    def test_update_org_webhook(self) -> None:
        """Test case for update_org_webhook

        Update webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
