# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipment_request_parcels_inner_order_lines_inner import CreateShipmentRequestParcelsInnerOrderLinesInner

class TestCreateShipmentRequestParcelsInnerOrderLinesInner(unittest.TestCase):
    """CreateShipmentRequestParcelsInnerOrderLinesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShipmentRequestParcelsInnerOrderLinesInner:
        """Test CreateShipmentRequestParcelsInnerOrderLinesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShipmentRequestParcelsInnerOrderLinesInner`
        """
        model = CreateShipmentRequestParcelsInnerOrderLinesInner()
        if include_optional:
            return CreateShipmentRequestParcelsInnerOrderLinesInner(
                id = 'ol_9c1d2e3f',
                sku = 'SKU-1024',
                quantity = 2,
                description = 'Wool sweater, navy',
                unit_price = 299.95,
                currency = 'DKK',
                vat_percent = 25,
                location = 'A-12-3',
                country_of_origin = 'DK',
                tarrif_number = '61101100'
            )
        else:
            return CreateShipmentRequestParcelsInnerOrderLinesInner(
                sku = 'SKU-1024',
                quantity = 2,
        )
        """

    def testCreateShipmentRequestParcelsInnerOrderLinesInner(self):
        """Test CreateShipmentRequestParcelsInnerOrderLinesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
