# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipment201_response_activities_inner import CreateShipment201ResponseActivitiesInner

class TestCreateShipment201ResponseActivitiesInner(unittest.TestCase):
    """CreateShipment201ResponseActivitiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShipment201ResponseActivitiesInner:
        """Test CreateShipment201ResponseActivitiesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShipment201ResponseActivitiesInner`
        """
        model = CreateShipment201ResponseActivitiesInner()
        if include_optional:
            return CreateShipment201ResponseActivitiesInner(
                id = 'act_1d2e3f4a',
                action = 'created',
                description = 'Shipment created',
                metadata = None,
                created_at = '2026-06-22T14:30:00.000Z'
            )
        else:
            return CreateShipment201ResponseActivitiesInner(
                id = 'act_1d2e3f4a',
                action = 'created',
                description = 'Shipment created',
                created_at = '2026-06-22T14:30:00.000Z',
        )
        """

    def testCreateShipment201ResponseActivitiesInner(self):
        """Test CreateShipment201ResponseActivitiesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
