# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.list_api_tokens200_response_data_inner_created_by import ListApiTokens200ResponseDataInnerCreatedBy

class TestListApiTokens200ResponseDataInnerCreatedBy(unittest.TestCase):
    """ListApiTokens200ResponseDataInnerCreatedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListApiTokens200ResponseDataInnerCreatedBy:
        """Test ListApiTokens200ResponseDataInnerCreatedBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListApiTokens200ResponseDataInnerCreatedBy`
        """
        model = ListApiTokens200ResponseDataInnerCreatedBy()
        if include_optional:
            return ListApiTokens200ResponseDataInnerCreatedBy(
                id = 'usr_9f3kd92ld0',
                name = 'Anna Jensen',
                email = 'anna@example.dk'
            )
        else:
            return ListApiTokens200ResponseDataInnerCreatedBy(
                id = 'usr_9f3kd92ld0',
                name = 'Anna Jensen',
                email = 'anna@example.dk',
        )
        """

    def testListApiTokens200ResponseDataInnerCreatedBy(self):
        """Test ListApiTokens200ResponseDataInnerCreatedBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
