# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zippendo.models.create_shipping_rule_request_conditions_inner_one_of3 import CreateShippingRuleRequestConditionsInnerOneOf3

class TestCreateShippingRuleRequestConditionsInnerOneOf3(unittest.TestCase):
    """CreateShippingRuleRequestConditionsInnerOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShippingRuleRequestConditionsInnerOneOf3:
        """Test CreateShippingRuleRequestConditionsInnerOneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShippingRuleRequestConditionsInnerOneOf3`
        """
        model = CreateShippingRuleRequestConditionsInnerOneOf3()
        if include_optional:
            return CreateShippingRuleRequestConditionsInnerOneOf3(
                type = 'quantity',
                operator = 'gte',
                value = 3,
                shipping_price = 0,
                currency = 'DKK'
            )
        else:
            return CreateShippingRuleRequestConditionsInnerOneOf3(
                type = 'quantity',
                operator = 'gte',
                value = 3,
                shipping_price = 0,
                currency = 'DKK',
        )
        """

    def testCreateShippingRuleRequestConditionsInnerOneOf3(self):
        """Test CreateShippingRuleRequestConditionsInnerOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
