# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from zippendo.models.create_shipping_rule_request_conditions_inner_one_of import CreateShippingRuleRequestConditionsInnerOneOf
from zippendo.models.create_shipping_rule_request_conditions_inner_one_of1 import CreateShippingRuleRequestConditionsInnerOneOf1
from zippendo.models.create_shipping_rule_request_conditions_inner_one_of2 import CreateShippingRuleRequestConditionsInnerOneOf2
from zippendo.models.create_shipping_rule_request_conditions_inner_one_of3 import CreateShippingRuleRequestConditionsInnerOneOf3
from zippendo.models.create_shipping_rule_request_conditions_inner_one_of4 import CreateShippingRuleRequestConditionsInnerOneOf4
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CREATESHIPPINGRULEREQUESTCONDITIONSINNER_ONE_OF_SCHEMAS = ["CreateShippingRuleRequestConditionsInnerOneOf", "CreateShippingRuleRequestConditionsInnerOneOf1", "CreateShippingRuleRequestConditionsInnerOneOf2", "CreateShippingRuleRequestConditionsInnerOneOf3", "CreateShippingRuleRequestConditionsInnerOneOf4"]

class CreateShippingRuleRequestConditionsInner(BaseModel):
    """
    CreateShippingRuleRequestConditionsInner
    """
    # data type: CreateShippingRuleRequestConditionsInnerOneOf
    oneof_schema_1_validator: Optional[CreateShippingRuleRequestConditionsInnerOneOf] = None
    # data type: CreateShippingRuleRequestConditionsInnerOneOf1
    oneof_schema_2_validator: Optional[CreateShippingRuleRequestConditionsInnerOneOf1] = None
    # data type: CreateShippingRuleRequestConditionsInnerOneOf2
    oneof_schema_3_validator: Optional[CreateShippingRuleRequestConditionsInnerOneOf2] = None
    # data type: CreateShippingRuleRequestConditionsInnerOneOf3
    oneof_schema_4_validator: Optional[CreateShippingRuleRequestConditionsInnerOneOf3] = None
    # data type: CreateShippingRuleRequestConditionsInnerOneOf4
    oneof_schema_5_validator: Optional[CreateShippingRuleRequestConditionsInnerOneOf4] = None
    actual_instance: Optional[Union[CreateShippingRuleRequestConditionsInnerOneOf, CreateShippingRuleRequestConditionsInnerOneOf1, CreateShippingRuleRequestConditionsInnerOneOf2, CreateShippingRuleRequestConditionsInnerOneOf3, CreateShippingRuleRequestConditionsInnerOneOf4]] = None
    one_of_schemas: Set[str] = { "CreateShippingRuleRequestConditionsInnerOneOf", "CreateShippingRuleRequestConditionsInnerOneOf1", "CreateShippingRuleRequestConditionsInnerOneOf2", "CreateShippingRuleRequestConditionsInnerOneOf3", "CreateShippingRuleRequestConditionsInnerOneOf4" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = CreateShippingRuleRequestConditionsInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: CreateShippingRuleRequestConditionsInnerOneOf
        if not isinstance(v, CreateShippingRuleRequestConditionsInnerOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateShippingRuleRequestConditionsInnerOneOf`")
        else:
            match += 1
        # validate data type: CreateShippingRuleRequestConditionsInnerOneOf1
        if not isinstance(v, CreateShippingRuleRequestConditionsInnerOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateShippingRuleRequestConditionsInnerOneOf1`")
        else:
            match += 1
        # validate data type: CreateShippingRuleRequestConditionsInnerOneOf2
        if not isinstance(v, CreateShippingRuleRequestConditionsInnerOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateShippingRuleRequestConditionsInnerOneOf2`")
        else:
            match += 1
        # validate data type: CreateShippingRuleRequestConditionsInnerOneOf3
        if not isinstance(v, CreateShippingRuleRequestConditionsInnerOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateShippingRuleRequestConditionsInnerOneOf3`")
        else:
            match += 1
        # validate data type: CreateShippingRuleRequestConditionsInnerOneOf4
        if not isinstance(v, CreateShippingRuleRequestConditionsInnerOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateShippingRuleRequestConditionsInnerOneOf4`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in CreateShippingRuleRequestConditionsInner with oneOf schemas: CreateShippingRuleRequestConditionsInnerOneOf, CreateShippingRuleRequestConditionsInnerOneOf1, CreateShippingRuleRequestConditionsInnerOneOf2, CreateShippingRuleRequestConditionsInnerOneOf3, CreateShippingRuleRequestConditionsInnerOneOf4. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in CreateShippingRuleRequestConditionsInner with oneOf schemas: CreateShippingRuleRequestConditionsInnerOneOf, CreateShippingRuleRequestConditionsInnerOneOf1, CreateShippingRuleRequestConditionsInnerOneOf2, CreateShippingRuleRequestConditionsInnerOneOf3, CreateShippingRuleRequestConditionsInnerOneOf4. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into CreateShippingRuleRequestConditionsInnerOneOf
        try:
            instance.actual_instance = CreateShippingRuleRequestConditionsInnerOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CreateShippingRuleRequestConditionsInnerOneOf1
        try:
            instance.actual_instance = CreateShippingRuleRequestConditionsInnerOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CreateShippingRuleRequestConditionsInnerOneOf2
        try:
            instance.actual_instance = CreateShippingRuleRequestConditionsInnerOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CreateShippingRuleRequestConditionsInnerOneOf3
        try:
            instance.actual_instance = CreateShippingRuleRequestConditionsInnerOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CreateShippingRuleRequestConditionsInnerOneOf4
        try:
            instance.actual_instance = CreateShippingRuleRequestConditionsInnerOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CreateShippingRuleRequestConditionsInner with oneOf schemas: CreateShippingRuleRequestConditionsInnerOneOf, CreateShippingRuleRequestConditionsInnerOneOf1, CreateShippingRuleRequestConditionsInnerOneOf2, CreateShippingRuleRequestConditionsInnerOneOf3, CreateShippingRuleRequestConditionsInnerOneOf4. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CreateShippingRuleRequestConditionsInner with oneOf schemas: CreateShippingRuleRequestConditionsInnerOneOf, CreateShippingRuleRequestConditionsInnerOneOf1, CreateShippingRuleRequestConditionsInnerOneOf2, CreateShippingRuleRequestConditionsInnerOneOf3, CreateShippingRuleRequestConditionsInnerOneOf4. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CreateShippingRuleRequestConditionsInnerOneOf, CreateShippingRuleRequestConditionsInnerOneOf1, CreateShippingRuleRequestConditionsInnerOneOf2, CreateShippingRuleRequestConditionsInnerOneOf3, CreateShippingRuleRequestConditionsInnerOneOf4]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


