# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateOrderRequestOrderLinesInner(BaseModel):
    """
    CreateOrderRequestOrderLinesInner
    """ # noqa: E501
    sku: Optional[StrictStr] = Field(default=None, description="Stock keeping unit identifier.", json_schema_extra={"examples": ["SKU-1042-BLK"]})
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Product name.", json_schema_extra={"examples": ["Wool Sweater"]})
    quantity: Annotated[int, Field(le=9007199254740991, strict=True, gt=0)] = Field(description="Quantity ordered.", json_schema_extra={"examples": [2]})
    unit_price: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Price per unit.", alias="unitPrice", json_schema_extra={"examples": [499]})
    total_price: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Total price for the line.", alias="totalPrice", json_schema_extra={"examples": [998]})
    currency: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=3)]] = Field(default=None, description="ISO 4217 currency code.", json_schema_extra={"examples": ["DKK"]})
    weight: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Item weight in the given unit.", json_schema_extra={"examples": [0.5]})
    weight_unit: Optional[StrictStr] = Field(default=None, description="Unit of the weight value.", alias="weightUnit", json_schema_extra={"examples": ["kg"]})
    variant_id: Optional[StrictStr] = Field(default=None, description="Platform variant identifier.", alias="variantId", json_schema_extra={"examples": ["44218900291"]})
    product_id: Optional[StrictStr] = Field(default=None, description="Platform product identifier.", alias="productId", json_schema_extra={"examples": ["8123456789"]})
    image_url: Optional[StrictStr] = Field(default=None, description="Product image URL.", alias="imageUrl", json_schema_extra={"examples": ["https://cdn.example.dk/products/sweater.jpg"]})
    hs_code: Optional[StrictStr] = Field(default=None, description="Harmonized System customs code (6-13 digits).", alias="hsCode", json_schema_extra={"examples": ["611020"]})
    country_of_origin: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2)]] = Field(default=None, description="ISO 3166-1 alpha-2 country of origin.", alias="countryOfOrigin", json_schema_extra={"examples": ["DK"]})
    province_of_origin: Optional[StrictStr] = Field(default=None, description="ISO 3166-2 province of origin.", alias="provinceOfOrigin", json_schema_extra={"examples": ["DK-84"]})
    barcode: Optional[StrictStr] = Field(default=None, description="Item barcode (EAN/UPC).", json_schema_extra={"examples": ["5712345678901"]})
    requires_shipping: Optional[StrictBool] = Field(default=None, description="Whether the item requires shipping.", alias="requiresShipping", json_schema_extra={"examples": [True]})
    taxable: Optional[StrictBool] = Field(default=None, description="Whether the item is taxable.", json_schema_extra={"examples": [True]})
    gift_card: Optional[StrictBool] = Field(default=None, description="Whether the item is a gift card.", alias="giftCard", json_schema_extra={"examples": [False]})
    vendor: Optional[StrictStr] = Field(default=None, description="Vendor or brand name.", json_schema_extra={"examples": ["Norse Knits"]})
    __properties: ClassVar[List[str]] = ["sku", "name", "quantity", "unitPrice", "totalPrice", "currency", "weight", "weightUnit", "variantId", "productId", "imageUrl", "hsCode", "countryOfOrigin", "provinceOfOrigin", "barcode", "requiresShipping", "taxable", "giftCard", "vendor"]

    @field_validator('weight_unit')
    def weight_unit_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kg', 'g', 'lb', 'oz']):
            raise ValueError("must be one of enum values ('kg', 'g', 'lb', 'oz')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrderRequestOrderLinesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sku (nullable) is None
        # and model_fields_set contains the field
        if self.sku is None and "sku" in self.model_fields_set:
            _dict['sku'] = None

        # set to None if unit_price (nullable) is None
        # and model_fields_set contains the field
        if self.unit_price is None and "unit_price" in self.model_fields_set:
            _dict['unitPrice'] = None

        # set to None if total_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_price is None and "total_price" in self.model_fields_set:
            _dict['totalPrice'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if weight (nullable) is None
        # and model_fields_set contains the field
        if self.weight is None and "weight" in self.model_fields_set:
            _dict['weight'] = None

        # set to None if weight_unit (nullable) is None
        # and model_fields_set contains the field
        if self.weight_unit is None and "weight_unit" in self.model_fields_set:
            _dict['weightUnit'] = None

        # set to None if variant_id (nullable) is None
        # and model_fields_set contains the field
        if self.variant_id is None and "variant_id" in self.model_fields_set:
            _dict['variantId'] = None

        # set to None if product_id (nullable) is None
        # and model_fields_set contains the field
        if self.product_id is None and "product_id" in self.model_fields_set:
            _dict['productId'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['imageUrl'] = None

        # set to None if hs_code (nullable) is None
        # and model_fields_set contains the field
        if self.hs_code is None and "hs_code" in self.model_fields_set:
            _dict['hsCode'] = None

        # set to None if country_of_origin (nullable) is None
        # and model_fields_set contains the field
        if self.country_of_origin is None and "country_of_origin" in self.model_fields_set:
            _dict['countryOfOrigin'] = None

        # set to None if province_of_origin (nullable) is None
        # and model_fields_set contains the field
        if self.province_of_origin is None and "province_of_origin" in self.model_fields_set:
            _dict['provinceOfOrigin'] = None

        # set to None if barcode (nullable) is None
        # and model_fields_set contains the field
        if self.barcode is None and "barcode" in self.model_fields_set:
            _dict['barcode'] = None

        # set to None if requires_shipping (nullable) is None
        # and model_fields_set contains the field
        if self.requires_shipping is None and "requires_shipping" in self.model_fields_set:
            _dict['requiresShipping'] = None

        # set to None if taxable (nullable) is None
        # and model_fields_set contains the field
        if self.taxable is None and "taxable" in self.model_fields_set:
            _dict['taxable'] = None

        # set to None if gift_card (nullable) is None
        # and model_fields_set contains the field
        if self.gift_card is None and "gift_card" in self.model_fields_set:
            _dict['giftCard'] = None

        # set to None if vendor (nullable) is None
        # and model_fields_set contains the field
        if self.vendor is None and "vendor" in self.model_fields_set:
            _dict['vendor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrderRequestOrderLinesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sku": obj.get("sku"),
            "name": obj.get("name"),
            "quantity": obj.get("quantity"),
            "unitPrice": obj.get("unitPrice"),
            "totalPrice": obj.get("totalPrice"),
            "currency": obj.get("currency"),
            "weight": obj.get("weight"),
            "weightUnit": obj.get("weightUnit"),
            "variantId": obj.get("variantId"),
            "productId": obj.get("productId"),
            "imageUrl": obj.get("imageUrl"),
            "hsCode": obj.get("hsCode"),
            "countryOfOrigin": obj.get("countryOfOrigin"),
            "provinceOfOrigin": obj.get("provinceOfOrigin"),
            "barcode": obj.get("barcode"),
            "requiresShipping": obj.get("requiresShipping"),
            "taxable": obj.get("taxable"),
            "giftCard": obj.get("giftCard"),
            "vendor": obj.get("vendor")
        })
        return _obj


