# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateShippingRuleRequestConditionsInnerOneOf2(BaseModel):
    """
    CreateShippingRuleRequestConditionsInnerOneOf2
    """ # noqa: E501
    type: StrictStr = Field(description="Condition type discriminator", json_schema_extra={"examples": ["priceRange"]})
    price_type: Optional[StrictStr] = Field(default='total', description="Whether to compare against subtotal (before discounts) or total (after discounts)", alias="priceType", json_schema_extra={"examples": ["total"]})
    min: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Minimum cart value (inclusive)", json_schema_extra={"examples": [0]})
    max: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Maximum cart value (inclusive)", json_schema_extra={"examples": [499]})
    shipping_price: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Shipping price when condition matches", alias="shippingPrice", json_schema_extra={"examples": [49]})
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="ISO 4217 currency code", json_schema_extra={"examples": ["DKK"]})
    __properties: ClassVar[List[str]] = ["type", "priceType", "min", "max", "shippingPrice", "currency"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['priceRange']):
            raise ValueError("must be one of enum values ('priceRange')")
        return value

    @field_validator('price_type')
    def price_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['subtotal', 'total']):
            raise ValueError("must be one of enum values ('subtotal', 'total')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateShippingRuleRequestConditionsInnerOneOf2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateShippingRuleRequestConditionsInnerOneOf2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "priceType": obj.get("priceType") if obj.get("priceType") is not None else 'total',
            "min": obj.get("min"),
            "max": obj.get("max"),
            "shippingPrice": obj.get("shippingPrice"),
            "currency": obj.get("currency")
        })
        return _obj


