# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Dict, List, Optional
from zippendo.models.create_shipping_rule_request_additional_parameters_any_of_inner import CreateShippingRuleRequestAdditionalParametersAnyOfInner
from zippendo.models.create_shipping_rule_request_additional_parameters_any_of_value import CreateShippingRuleRequestAdditionalParametersAnyOfValue
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

CREATESHIPPINGRULEREQUESTADDITIONALPARAMETERS_ANY_OF_SCHEMAS = ["Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue]", "List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]"]

class CreateShippingRuleRequestAdditionalParameters(BaseModel):
    """
    Carrier-specific extra parameters. Accepts EITHER the `{ key: value }` object (preferred) OR the legacy `[{ name, val }]` array, so you can migrate on your own schedule. Each key / `name` is the carrier parameter `key` from the product's `additionalParameters[].key` (e.g. `returnFunctionality`).
    """

    # data type: List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]
    anyof_schema_1_validator: Optional[List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]] = None
    # data type: Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue]
    anyof_schema_2_validator: Optional[Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue]] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue], List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue]", "List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = CreateShippingRuleRequestAdditionalParameters.model_construct()
        error_messages = []
        # validate data type: List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]
        try:
            instance.anyof_schema_1_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue]
        try:
            instance.anyof_schema_2_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in CreateShippingRuleRequestAdditionalParameters with anyOf schemas: Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue], List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # deserialize data into List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]
        try:
            # validation
            instance.anyof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_1_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue]
        try:
            # validation
            instance.anyof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_2_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CreateShippingRuleRequestAdditionalParameters with anyOf schemas: Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue], List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue], List[CreateShippingRuleRequestAdditionalParametersAnyOfInner]]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


