# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateShippingQuote200ResponseRatesInner(BaseModel):
    """
    CreateShippingQuote200ResponseRatesInner
    """ # noqa: E501
    service_name: StrictStr = Field(description="Display name of the shipping option", alias="serviceName", json_schema_extra={"examples": ["Standard DK"]})
    service_code: StrictStr = Field(description="Unique identifier for this shipping option", alias="serviceCode", json_schema_extra={"examples": ["postnord:PNL13:rule_01HZX9K2QF"]})
    total_price: StrictStr = Field(description="Total shipping price in cents as string", alias="totalPrice", json_schema_extra={"examples": ["3900"]})
    currency: StrictStr = Field(description="ISO 4217 currency code", json_schema_extra={"examples": ["DKK"]})
    description: Optional[StrictStr] = Field(default=None, description="Optional description", json_schema_extra={"examples": ["Standard levering i Danmark"]})
    min_delivery_date: Optional[StrictStr] = Field(default=None, description="Minimum delivery date (ISO 8601)", alias="minDeliveryDate", json_schema_extra={"examples": ["2026-06-24"]})
    max_delivery_date: Optional[StrictStr] = Field(default=None, description="Maximum delivery date (ISO 8601)", alias="maxDeliveryDate", json_schema_extra={"examples": ["2026-06-26"]})
    carrier_name: Optional[StrictStr] = Field(default=None, description="Carrier display name", alias="carrierName", json_schema_extra={"examples": ["PostNord"]})
    carrier_slug: Optional[StrictStr] = Field(default=None, description="Carrier slug identifier", alias="carrierSlug", json_schema_extra={"examples": ["postnord"]})
    product_id: Optional[StrictStr] = Field(default=None, description="Carrier product ID", alias="productId", json_schema_extra={"examples": ["PNL13"]})
    shipping_rule_id: StrictStr = Field(description="Shipping rule ID that generated this rate", alias="shippingRuleId", json_schema_extra={"examples": ["rule_01HZX9K2QF"]})
    __properties: ClassVar[List[str]] = ["serviceName", "serviceCode", "totalPrice", "currency", "description", "minDeliveryDate", "maxDeliveryDate", "carrierName", "carrierSlug", "productId", "shippingRuleId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateShippingQuote200ResponseRatesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateShippingQuote200ResponseRatesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "serviceName": obj.get("serviceName"),
            "serviceCode": obj.get("serviceCode"),
            "totalPrice": obj.get("totalPrice"),
            "currency": obj.get("currency"),
            "description": obj.get("description"),
            "minDeliveryDate": obj.get("minDeliveryDate"),
            "maxDeliveryDate": obj.get("maxDeliveryDate"),
            "carrierName": obj.get("carrierName"),
            "carrierSlug": obj.get("carrierSlug"),
            "productId": obj.get("productId"),
            "shippingRuleId": obj.get("shippingRuleId")
        })
        return _obj


