# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from zippendo.models.create_shipment201_response_activities_inner import CreateShipment201ResponseActivitiesInner
from zippendo.models.create_shipment201_response_documents_inner import CreateShipment201ResponseDocumentsInner
from zippendo.models.create_shipment201_response_errors_inner import CreateShipment201ResponseErrorsInner
from zippendo.models.create_shipment201_response_logs_inner import CreateShipment201ResponseLogsInner
from zippendo.models.create_shipment201_response_parcels_inner import CreateShipment201ResponseParcelsInner
from zippendo.models.create_shipment201_response_parties_inner import CreateShipment201ResponsePartiesInner
from zippendo.models.create_shipment201_response_pickup_details import CreateShipment201ResponsePickupDetails
from zippendo.models.create_shipment201_response_shipping_rule import CreateShipment201ResponseShippingRule
from zippendo.models.create_shipment201_response_tracking import CreateShipment201ResponseTracking
from zippendo.models.list_shipments200_response_data_inner_carrier_settings import ListShipments200ResponseDataInnerCarrierSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateShipment201Response(BaseModel):
    """
    CreateShipment201Response
    """ # noqa: E501
    id: StrictStr = Field(description="Unique shipment identifier.", json_schema_extra={"examples": ["shp_4d9e7a2f"]})
    reference: StrictStr = Field(description="Customer-facing shipment reference.", json_schema_extra={"examples": ["ORDER-1042"]})
    address_id: Optional[StrictStr] = Field(default=None, description="Sender address identifier.", alias="addressId", json_schema_extra={"examples": ["addr_7e8f9a0b"]})
    service_point_id: Optional[StrictStr] = Field(default=None, description="Selected carrier service point identifier.", alias="servicePointId", json_schema_extra={"examples": ["sp_pn_4521"]})
    parties: List[CreateShipment201ResponsePartiesInner] = Field(description="Parties involved in the shipment (sender, receiver, etc.).")
    type: StrictStr = Field(description="Direction of the shipment relative to the organization.", json_schema_extra={"examples": ["outbound"]})
    carrier_settings: ListShipments200ResponseDataInnerCarrierSettings = Field(alias="carrierSettings")
    parcels: List[CreateShipment201ResponseParcelsInner] = Field(description="Parcels included in the shipment.")
    pickup_details: Optional[CreateShipment201ResponsePickupDetails] = Field(default=None, alias="pickupDetails")
    term_of_trade: StrictStr = Field(description="Incoterm governing the shipment.", alias="termOfTrade", json_schema_extra={"examples": ["DAP"]})
    documents: Optional[List[CreateShipment201ResponseDocumentsInner]] = Field(default=None, description="Documents generated for the shipment (labels, invoices).")
    errors: List[CreateShipment201ResponseErrorsInner] = Field(description="Carrier errors recorded for the shipment.")
    tracking: Optional[CreateShipment201ResponseTracking] = None
    status: StrictStr = Field(description="Lifecycle status of the shipment.", json_schema_extra={"examples": ["pending"]})
    org_id: StrictStr = Field(description="Owning organization identifier.", alias="orgId", json_schema_extra={"examples": ["org_1a2b3c4d"]})
    order_id: Optional[StrictStr] = Field(default=None, description="Associated order identifier.", alias="orderId", json_schema_extra={"examples": ["ord_5e6f7a8b"]})
    shipping_rule_id: Optional[StrictStr] = Field(default=None, description="Applied shipping rule identifier.", alias="shippingRuleId", json_schema_extra={"examples": ["rule_3c4d5e6f"]})
    shipping_rule: Optional[CreateShipment201ResponseShippingRule] = Field(default=None, alias="shippingRule")
    label_printer_id: Optional[StrictStr] = Field(default=None, description="Printer assigned for labels on this shipment.", alias="labelPrinterId", json_schema_extra={"examples": ["prn_label_01"]})
    document_printer_id: Optional[StrictStr] = Field(default=None, description="Printer assigned for documents on this shipment.", alias="documentPrinterId", json_schema_extra={"examples": ["prn_doc_01"]})
    logs: List[CreateShipment201ResponseLogsInner] = Field(description="Request/response logs captured during carrier interactions.")
    activities: List[CreateShipment201ResponseActivitiesInner] = Field(description="Chronological activity history of the shipment.")
    created_at: StrictStr = Field(description="Timestamp when the shipment was created.", alias="createdAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    updated_at: StrictStr = Field(description="Timestamp when the shipment was last updated.", alias="updatedAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    __properties: ClassVar[List[str]] = ["id", "reference", "addressId", "servicePointId", "parties", "type", "carrierSettings", "parcels", "pickupDetails", "termOfTrade", "documents", "errors", "tracking", "status", "orgId", "orderId", "shippingRuleId", "shippingRule", "labelPrinterId", "documentPrinterId", "logs", "activities", "createdAt", "updatedAt"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['outbound', 'inbound']):
            raise ValueError("must be one of enum values ('outbound', 'inbound')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['draft', 'pending', 'processing', 'dispatched', 'partly_dispatched', 'error', 'cancelled', 'on_hold']):
            raise ValueError("must be one of enum values ('draft', 'pending', 'processing', 'dispatched', 'partly_dispatched', 'error', 'cancelled', 'on_hold')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateShipment201Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parties (list)
        _items = []
        if self.parties:
            for _item_parties in self.parties:
                if _item_parties:
                    _items.append(_item_parties.to_dict())
            _dict['parties'] = _items
        # override the default output from pydantic by calling `to_dict()` of carrier_settings
        if self.carrier_settings:
            _dict['carrierSettings'] = self.carrier_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in parcels (list)
        _items = []
        if self.parcels:
            for _item_parcels in self.parcels:
                if _item_parcels:
                    _items.append(_item_parcels.to_dict())
            _dict['parcels'] = _items
        # override the default output from pydantic by calling `to_dict()` of pickup_details
        if self.pickup_details:
            _dict['pickupDetails'] = self.pickup_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item_documents in self.documents:
                if _item_documents:
                    _items.append(_item_documents.to_dict())
            _dict['documents'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        # override the default output from pydantic by calling `to_dict()` of tracking
        if self.tracking:
            _dict['tracking'] = self.tracking.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_rule
        if self.shipping_rule:
            _dict['shippingRule'] = self.shipping_rule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in logs (list)
        _items = []
        if self.logs:
            for _item_logs in self.logs:
                if _item_logs:
                    _items.append(_item_logs.to_dict())
            _dict['logs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities (list)
        _items = []
        if self.activities:
            for _item_activities in self.activities:
                if _item_activities:
                    _items.append(_item_activities.to_dict())
            _dict['activities'] = _items
        # set to None if address_id (nullable) is None
        # and model_fields_set contains the field
        if self.address_id is None and "address_id" in self.model_fields_set:
            _dict['addressId'] = None

        # set to None if service_point_id (nullable) is None
        # and model_fields_set contains the field
        if self.service_point_id is None and "service_point_id" in self.model_fields_set:
            _dict['servicePointId'] = None

        # set to None if pickup_details (nullable) is None
        # and model_fields_set contains the field
        if self.pickup_details is None and "pickup_details" in self.model_fields_set:
            _dict['pickupDetails'] = None

        # set to None if tracking (nullable) is None
        # and model_fields_set contains the field
        if self.tracking is None and "tracking" in self.model_fields_set:
            _dict['tracking'] = None

        # set to None if order_id (nullable) is None
        # and model_fields_set contains the field
        if self.order_id is None and "order_id" in self.model_fields_set:
            _dict['orderId'] = None

        # set to None if shipping_rule_id (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_rule_id is None and "shipping_rule_id" in self.model_fields_set:
            _dict['shippingRuleId'] = None

        # set to None if shipping_rule (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_rule is None and "shipping_rule" in self.model_fields_set:
            _dict['shippingRule'] = None

        # set to None if label_printer_id (nullable) is None
        # and model_fields_set contains the field
        if self.label_printer_id is None and "label_printer_id" in self.model_fields_set:
            _dict['labelPrinterId'] = None

        # set to None if document_printer_id (nullable) is None
        # and model_fields_set contains the field
        if self.document_printer_id is None and "document_printer_id" in self.model_fields_set:
            _dict['documentPrinterId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateShipment201Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "reference": obj.get("reference"),
            "addressId": obj.get("addressId"),
            "servicePointId": obj.get("servicePointId"),
            "parties": [CreateShipment201ResponsePartiesInner.from_dict(_item) for _item in obj["parties"]] if obj.get("parties") is not None else None,
            "type": obj.get("type"),
            "carrierSettings": ListShipments200ResponseDataInnerCarrierSettings.from_dict(obj["carrierSettings"]) if obj.get("carrierSettings") is not None else None,
            "parcels": [CreateShipment201ResponseParcelsInner.from_dict(_item) for _item in obj["parcels"]] if obj.get("parcels") is not None else None,
            "pickupDetails": CreateShipment201ResponsePickupDetails.from_dict(obj["pickupDetails"]) if obj.get("pickupDetails") is not None else None,
            "termOfTrade": obj.get("termOfTrade") if obj.get("termOfTrade") is not None else 'DAP',
            "documents": [CreateShipment201ResponseDocumentsInner.from_dict(_item) for _item in obj["documents"]] if obj.get("documents") is not None else None,
            "errors": [CreateShipment201ResponseErrorsInner.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None,
            "tracking": CreateShipment201ResponseTracking.from_dict(obj["tracking"]) if obj.get("tracking") is not None else None,
            "status": obj.get("status"),
            "orgId": obj.get("orgId"),
            "orderId": obj.get("orderId"),
            "shippingRuleId": obj.get("shippingRuleId"),
            "shippingRule": CreateShipment201ResponseShippingRule.from_dict(obj["shippingRule"]) if obj.get("shippingRule") is not None else None,
            "labelPrinterId": obj.get("labelPrinterId"),
            "documentPrinterId": obj.get("documentPrinterId"),
            "logs": [CreateShipment201ResponseLogsInner.from_dict(_item) for _item in obj["logs"]] if obj.get("logs") is not None else None,
            "activities": [CreateShipment201ResponseActivitiesInner.from_dict(_item) for _item in obj["activities"]] if obj.get("activities") is not None else None,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


