# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateAddressRequest(BaseModel):
    """
    CreateAddressRequest
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Name of the address", json_schema_extra={"examples": ["Hovedlager"]})
    att_contact: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Attention contact person", alias="attContact", json_schema_extra={"examples": ["Mette Hansen"]})
    address1: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Address line 1", json_schema_extra={"examples": ["Vesterbrogade 1"]})
    address2: Optional[StrictStr] = Field(default=None, description="Address line 2", json_schema_extra={"examples": ["2. sal"]})
    zipcode: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Postal/ZIP code", json_schema_extra={"examples": ["1620"]})
    city: Annotated[str, Field(min_length=1, strict=True)] = Field(description="City", json_schema_extra={"examples": ["København"]})
    phone: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Phone number", json_schema_extra={"examples": ["+4533123456"]})
    country_code: Annotated[str, Field(min_length=2, strict=True, max_length=3)] = Field(description="Country code (ISO 2 or 3 letter)", alias="countryCode", json_schema_extra={"examples": ["DK"]})
    state: Optional[StrictStr] = Field(default=None, description="State/Province", json_schema_extra={"examples": [""]})
    email: Annotated[str, Field(strict=True)] = Field(description="Email address", json_schema_extra={"examples": ["lager@example.dk"]})
    customs: Optional[Dict[str, StrictStr]] = Field(default=None, description="Customs identifiers (voec, eori, sprn, ioss, fda, duns)", json_schema_extra={"examples": [{"eori": "DK12345678"}]})
    address_types: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="Address types (sender, pickup, return)", alias="addressTypes", json_schema_extra={"examples": [["sender"]]})
    __properties: ClassVar[List[str]] = ["name", "attContact", "address1", "address2", "zipcode", "city", "phone", "countryCode", "state", "email", "customs", "addressTypes"]

    @field_validator('email', mode="before")
    def email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^(?!\.)(?!.*\.\.)([A-Za-z0-9_\'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$", value):
            raise ValueError(r"must validate the regular expression /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/")
        return value

    @field_validator('address_types')
    def address_types_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['sender', 'pickup', 'return']):
                raise ValueError("each list item must be one of ('sender', 'pickup', 'return')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAddressRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAddressRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "attContact": obj.get("attContact"),
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "zipcode": obj.get("zipcode"),
            "city": obj.get("city"),
            "phone": obj.get("phone"),
            "countryCode": obj.get("countryCode"),
            "state": obj.get("state"),
            "email": obj.get("email"),
            "customs": obj.get("customs"),
            "addressTypes": obj.get("addressTypes")
        })
        return _obj


