# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateApiToken201Response(BaseModel):
    """
    CreateApiToken201Response
    """ # noqa: E501
    id: StrictStr = Field(description="Unique API token identifier", json_schema_extra={"examples": ["tok_6e2fa83ij9"]})
    name: StrictStr = Field(description="Token name for identification", json_schema_extra={"examples": ["Warehouse integration"]})
    token_prefix: StrictStr = Field(description="First 12 chars of the token for identification", alias="tokenPrefix", json_schema_extra={"examples": ["zipp_live_8f"]})
    scopes: List[StrictStr] = Field(description="Permission scopes granted by the token", json_schema_extra={"examples": [["read:shipments", "write:shipments"]]})
    last_used_at: Optional[StrictStr] = Field(description="Timestamp the token was last used (ISO 8601), null if never used", alias="lastUsedAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    expires_at: Optional[StrictStr] = Field(description="Expiry timestamp (ISO 8601), null if it never expires", alias="expiresAt", json_schema_extra={"examples": ["2026-09-20T14:30:00.000Z"]})
    created_at: StrictStr = Field(description="Creation timestamp (ISO 8601)", alias="createdAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    token: StrictStr = Field(description="Full API token (only shown once)", json_schema_extra={"examples": ["zipp_live_8f3kd92ld0a7b6c5d4e3f2a1"]})
    __properties: ClassVar[List[str]] = ["id", "name", "tokenPrefix", "scopes", "lastUsedAt", "expiresAt", "createdAt", "token"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateApiToken201Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_used_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_at is None and "last_used_at" in self.model_fields_set:
            _dict['lastUsedAt'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateApiToken201Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "tokenPrefix": obj.get("tokenPrefix"),
            "scopes": obj.get("scopes"),
            "lastUsedAt": obj.get("lastUsedAt"),
            "expiresAt": obj.get("expiresAt"),
            "createdAt": obj.get("createdAt"),
            "token": obj.get("token")
        })
        return _obj


