# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from zippendo.models.create_shipping_rule_request_additional_parameters_any_of_value import CreateShippingRuleRequestAdditionalParametersAnyOfValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateShipmentRequestCarrierSettings(BaseModel):
    """
    CreateShipmentRequestCarrierSettings
    """ # noqa: E501
    carrier_id: StrictStr = Field(description="Identifier of the carrier to use.", alias="carrierId", json_schema_extra={"examples": ["car_pn_001"]})
    product_id: StrictStr = Field(description="Identifier of the carrier product/service.", alias="productId", json_schema_extra={"examples": ["prod_mypack_home"]})
    services: List[StrictStr] = Field(description="Additional service codes requested from the carrier.", json_schema_extra={"examples": [["A7"]]})
    additional_parameters: Dict[str, CreateShippingRuleRequestAdditionalParametersAnyOfValue] = Field(description="Carrier-specific extra parameters as key/value pairs.", alias="additionalParameters", json_schema_extra={"examples": [{"notificationEmail": "anna@example.dk"}]})
    __properties: ClassVar[List[str]] = ["carrierId", "productId", "services", "additionalParameters"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateShipmentRequestCarrierSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in additional_parameters (dict)
        _field_dict = {}
        if self.additional_parameters:
            for _key_additional_parameters in self.additional_parameters:
                if self.additional_parameters[_key_additional_parameters]:
                    _field_dict[_key_additional_parameters] = self.additional_parameters[_key_additional_parameters].to_dict()
            _dict['additionalParameters'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateShipmentRequestCarrierSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "carrierId": obj.get("carrierId"),
            "productId": obj.get("productId"),
            "services": obj.get("services"),
            "additionalParameters": dict(
                (_k, CreateShippingRuleRequestAdditionalParametersAnyOfValue.from_dict(_v))
                for _k, _v in obj["additionalParameters"].items()
            )
            if obj.get("additionalParameters") is not None
            else None
        })
        return _obj


