# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetBillingUsage200ResponseAddOnsInner(BaseModel):
    """
    GetBillingUsage200ResponseAddOnsInner
    """ # noqa: E501
    type: StrictStr = Field(description="Type of billing add-on", json_schema_extra={"examples": ["extra_carrier"]})
    quantity: Union[StrictFloat, StrictInt] = Field(description="Number of add-on units purchased", json_schema_extra={"examples": [2]})
    unit_price: Union[StrictFloat, StrictInt] = Field(description="Price per unit per month, in øre", alias="unitPrice", json_schema_extra={"examples": [9900]})
    total_price: Union[StrictFloat, StrictInt] = Field(description="Total price per month, in øre", alias="totalPrice", json_schema_extra={"examples": [19800]})
    __properties: ClassVar[List[str]] = ["type", "quantity", "unitPrice", "totalPrice"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['extra_carrier', 'extra_channel']):
            raise ValueError("must be one of enum values ('extra_carrier', 'extra_channel')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetBillingUsage200ResponseAddOnsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetBillingUsage200ResponseAddOnsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "quantity": obj.get("quantity"),
            "unitPrice": obj.get("unitPrice"),
            "totalPrice": obj.get("totalPrice")
        })
        return _obj


