# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from zippendo.models.get_billing_usage200_response_add_ons_inner import GetBillingUsage200ResponseAddOnsInner
from zippendo.models.get_billing_usage200_response_current_period import GetBillingUsage200ResponseCurrentPeriod
from zippendo.models.get_billing_usage200_response_limits import GetBillingUsage200ResponseLimits
from zippendo.models.get_billing_usage200_response_shipments import GetBillingUsage200ResponseShipments
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetBillingUsage200Response(BaseModel):
    """
    GetBillingUsage200Response
    """ # noqa: E501
    current_period: GetBillingUsage200ResponseCurrentPeriod = Field(alias="currentPeriod")
    shipments: GetBillingUsage200ResponseShipments
    limits: GetBillingUsage200ResponseLimits
    add_ons: List[GetBillingUsage200ResponseAddOnsInner] = Field(description="Active add-ons on the subscription", alias="addOns", json_schema_extra={"examples": [[]]})
    __properties: ClassVar[List[str]] = ["currentPeriod", "shipments", "limits", "addOns"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetBillingUsage200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_period
        if self.current_period:
            _dict['currentPeriod'] = self.current_period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipments
        if self.shipments:
            _dict['shipments'] = self.shipments.to_dict()
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict['limits'] = self.limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in add_ons (list)
        _items = []
        if self.add_ons:
            for _item_add_ons in self.add_ons:
                if _item_add_ons:
                    _items.append(_item_add_ons.to_dict())
            _dict['addOns'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetBillingUsage200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currentPeriod": GetBillingUsage200ResponseCurrentPeriod.from_dict(obj["currentPeriod"]) if obj.get("currentPeriod") is not None else None,
            "shipments": GetBillingUsage200ResponseShipments.from_dict(obj["shipments"]) if obj.get("shipments") is not None else None,
            "limits": GetBillingUsage200ResponseLimits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            "addOns": [GetBillingUsage200ResponseAddOnsInner.from_dict(_item) for _item in obj["addOns"]] if obj.get("addOns") is not None else None
        })
        return _obj


