# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from zippendo.models.list_api_tokens200_response_data_inner_created_by import ListApiTokens200ResponseDataInnerCreatedBy
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListApiTokens200ResponseDataInner(BaseModel):
    """
    ListApiTokens200ResponseDataInner
    """ # noqa: E501
    id: StrictStr = Field(description="Unique API token identifier", json_schema_extra={"examples": ["tok_6e2fa83ij9"]})
    name: StrictStr = Field(description="Token name for identification", json_schema_extra={"examples": ["Warehouse integration"]})
    token_prefix: StrictStr = Field(description="First 12 chars of the token for identification", alias="tokenPrefix", json_schema_extra={"examples": ["zipp_live_8f"]})
    scopes: List[StrictStr] = Field(description="Permission scopes granted by the token", json_schema_extra={"examples": [["read:shipments", "write:shipments"]]})
    brand_id: Optional[StrictStr] = Field(description="Brand this token is restricted to, or null for organization-wide access", alias="brandId", json_schema_extra={"examples": ["brnd_8f3kd92ld0"]})
    last_used_at: Optional[StrictStr] = Field(description="Timestamp the token was last used (ISO 8601), null if never used", alias="lastUsedAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    expires_at: Optional[StrictStr] = Field(description="Expiry timestamp (ISO 8601), null if it never expires", alias="expiresAt", json_schema_extra={"examples": ["2026-09-20T14:30:00.000Z"]})
    created_at: StrictStr = Field(description="Creation timestamp (ISO 8601)", alias="createdAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    created_by: ListApiTokens200ResponseDataInnerCreatedBy = Field(alias="createdBy")
    __properties: ClassVar[List[str]] = ["id", "name", "tokenPrefix", "scopes", "brandId", "lastUsedAt", "expiresAt", "createdAt", "createdBy"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListApiTokens200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # set to None if brand_id (nullable) is None
        # and model_fields_set contains the field
        if self.brand_id is None and "brand_id" in self.model_fields_set:
            _dict['brandId'] = None

        # set to None if last_used_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_at is None and "last_used_at" in self.model_fields_set:
            _dict['lastUsedAt'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListApiTokens200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "tokenPrefix": obj.get("tokenPrefix"),
            "scopes": obj.get("scopes"),
            "brandId": obj.get("brandId"),
            "lastUsedAt": obj.get("lastUsedAt"),
            "expiresAt": obj.get("expiresAt"),
            "createdAt": obj.get("createdAt"),
            "createdBy": ListApiTokens200ResponseDataInnerCreatedBy.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None
        })
        return _obj


