# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from zippendo.models.list_carrier_products200_response_inner_additional_parameters_inner_options_inner import ListCarrierProducts200ResponseInnerAdditionalParametersInnerOptionsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListAvailableCarriers200ResponseInnerRequiredFieldsInner(BaseModel):
    """
    ListAvailableCarriers200ResponseInnerRequiredFieldsInner
    """ # noqa: E501
    name: StrictStr = Field(description="Human-readable label for the configuration field", json_schema_extra={"examples": ["Customer number"]})
    key: StrictStr = Field(description="Machine key used to store the field value", json_schema_extra={"examples": ["customerNumber"]})
    type: StrictStr = Field(description="Data type of the configuration field", json_schema_extra={"examples": ["string"]})
    options: Optional[List[ListCarrierProducts200ResponseInnerAdditionalParametersInnerOptionsInner]] = Field(default=None, description="Selectable options for enum-type fields")
    description: StrictStr = Field(description="Help text describing the field", json_schema_extra={"examples": ["Your PostNord customer number"]})
    required: Optional[StrictBool] = Field(default=None, description="Whether the field is mandatory", json_schema_extra={"examples": [True]})
    __properties: ClassVar[List[str]] = ["name", "key", "type", "options", "description", "required"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['string', 'number', 'boolean', 'enum', 'date', 'array', 'object']):
            raise ValueError("must be one of enum values ('string', 'number', 'boolean', 'enum', 'date', 'array', 'object')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListAvailableCarriers200ResponseInnerRequiredFieldsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListAvailableCarriers200ResponseInnerRequiredFieldsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "key": obj.get("key"),
            "type": obj.get("type"),
            "options": [ListCarrierProducts200ResponseInnerAdditionalParametersInnerOptionsInner.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "description": obj.get("description"),
            "required": obj.get("required")
        })
        return _obj


