# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListOrgWebhookDeliveries200ResponseDataInner(BaseModel):
    """
    ListOrgWebhookDeliveries200ResponseDataInner
    """ # noqa: E501
    id: StrictStr = Field(description="Delivery log ID", json_schema_extra={"examples": ["whd_clx9z8y7x6"]})
    webhook_id: StrictStr = Field(description="ID of the webhook this delivery belongs to", alias="webhookId", json_schema_extra={"examples": ["wh_clx1a2b3c4"]})
    event: StrictStr = Field(description="Event type that was delivered", json_schema_extra={"examples": ["shipment.created"]})
    payload: Optional[Any] = Field(description="JSON payload that was sent", json_schema_extra={"examples": [{"id": "shp_123"}]})
    status_code: Optional[Union[StrictFloat, StrictInt]] = Field(description="HTTP status code returned by the endpoint", alias="statusCode", json_schema_extra={"examples": [200]})
    response: Optional[StrictStr] = Field(description="Response body returned by the endpoint", json_schema_extra={"examples": ["OK"]})
    duration: Optional[Union[StrictFloat, StrictInt]] = Field(description="Request duration in milliseconds", json_schema_extra={"examples": [142]})
    success: StrictBool = Field(description="Whether the delivery succeeded", json_schema_extra={"examples": [True]})
    attempt: Union[StrictFloat, StrictInt] = Field(description="Delivery attempt number", json_schema_extra={"examples": [1]})
    error: Optional[StrictStr] = Field(description="Error message if the delivery failed")
    created_at: StrictStr = Field(description="Delivery timestamp (ISO 8601)", alias="createdAt", json_schema_extra={"examples": ["2026-06-10T11:16:00.000Z"]})
    __properties: ClassVar[List[str]] = ["id", "webhookId", "event", "payload", "statusCode", "response", "duration", "success", "attempt", "error", "createdAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListOrgWebhookDeliveries200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if payload (nullable) is None
        # and model_fields_set contains the field
        if self.payload is None and "payload" in self.model_fields_set:
            _dict['payload'] = None

        # set to None if status_code (nullable) is None
        # and model_fields_set contains the field
        if self.status_code is None and "status_code" in self.model_fields_set:
            _dict['statusCode'] = None

        # set to None if response (nullable) is None
        # and model_fields_set contains the field
        if self.response is None and "response" in self.model_fields_set:
            _dict['response'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListOrgWebhookDeliveries200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "webhookId": obj.get("webhookId"),
            "event": obj.get("event"),
            "payload": obj.get("payload"),
            "statusCode": obj.get("statusCode"),
            "response": obj.get("response"),
            "duration": obj.get("duration"),
            "success": obj.get("success"),
            "attempt": obj.get("attempt"),
            "error": obj.get("error"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


