# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from zippendo.models.list_shipments200_response_data_inner_address import ListShipments200ResponseDataInnerAddress
from zippendo.models.list_shipments200_response_data_inner_carrier_settings import ListShipments200ResponseDataInnerCarrierSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListShipments200ResponseDataInner(BaseModel):
    """
    ListShipments200ResponseDataInner
    """ # noqa: E501
    id: StrictStr = Field(description="Unique shipment identifier.", json_schema_extra={"examples": ["shp_4d9e7a2f"]})
    reference: StrictStr = Field(description="Customer-facing shipment reference.", json_schema_extra={"examples": ["ORDER-1042"]})
    type: StrictStr = Field(description="Direction of the shipment relative to the organization.", json_schema_extra={"examples": ["outbound"]})
    carrier_settings: ListShipments200ResponseDataInnerCarrierSettings = Field(alias="carrierSettings")
    status: StrictStr = Field(description="Lifecycle status of the shipment.", json_schema_extra={"examples": ["pending"]})
    brand_id: Optional[StrictStr] = Field(description="Brand this record belongs to, or null when it is organization-wide", alias="brandId", json_schema_extra={"examples": ["brnd_8f3kd92ld0"]})
    address: Optional[ListShipments200ResponseDataInnerAddress] = None
    created_at: StrictStr = Field(description="Timestamp when the shipment was created.", alias="createdAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    updated_at: StrictStr = Field(description="Timestamp when the shipment was last updated.", alias="updatedAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    __properties: ClassVar[List[str]] = ["id", "reference", "type", "carrierSettings", "status", "brandId", "address", "createdAt", "updatedAt"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['outbound', 'inbound']):
            raise ValueError("must be one of enum values ('outbound', 'inbound')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['draft', 'pending', 'processing', 'dispatched', 'partly_dispatched', 'error', 'cancelled', 'on_hold']):
            raise ValueError("must be one of enum values ('draft', 'pending', 'processing', 'dispatched', 'partly_dispatched', 'error', 'cancelled', 'on_hold')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListShipments200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of carrier_settings
        if self.carrier_settings:
            _dict['carrierSettings'] = self.carrier_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # set to None if brand_id (nullable) is None
        # and model_fields_set contains the field
        if self.brand_id is None and "brand_id" in self.model_fields_set:
            _dict['brandId'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListShipments200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "reference": obj.get("reference"),
            "type": obj.get("type"),
            "carrierSettings": ListShipments200ResponseDataInnerCarrierSettings.from_dict(obj["carrierSettings"]) if obj.get("carrierSettings") is not None else None,
            "status": obj.get("status"),
            "brandId": obj.get("brandId"),
            "address": ListShipments200ResponseDataInnerAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


