# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from zippendo.models.list_shipping_rules200_response_data_inner_additional_parameters_value_any_of_coordinates_inner import ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf(BaseModel):
    """
    ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf
    """ # noqa: E501
    id: StrictStr = Field(description="Identifier of the selected service point.", json_schema_extra={"examples": ["sp_pn_4521"]})
    name: StrictStr = Field(description="Display name of the service point.", json_schema_extra={"examples": ["Føtex Nørrebro"]})
    address: StrictStr = Field(description="Formatted address of the service point.", json_schema_extra={"examples": ["Nørrebrogade 20, 2200 København N"]})
    coordinates: Optional[Annotated[List[ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner], Field(min_length=2, max_length=2)]] = Field(default=None, description="Latitude/longitude of the service point.", json_schema_extra={"examples": [[55.6987, 12.5501]]})
    __properties: ClassVar[List[str]] = ["id", "name", "address", "coordinates"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in coordinates (list)
        _items = []
        if self.coordinates:
            for _item_coordinates in self.coordinates:
                if _item_coordinates:
                    _items.append(_item_coordinates.to_dict())
            _dict['coordinates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "address": obj.get("address"),
            "coordinates": [ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner.from_dict(_item) for _item in obj["coordinates"]] if obj.get("coordinates") is not None else None
        })
        return _obj


