# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SplitShipmentRequest(BaseModel):
    """
    SplitShipmentRequest
    """ # noqa: E501
    parcel_id: StrictStr = Field(description="Parcel whose order lines are split into a new shipment.", alias="parcelId", json_schema_extra={"examples": ["prc_5a6b7c8d"]})
    order_line_ids: Optional[List[StrictStr]] = Field(default=None, description="Order line IDs to move. If omitted, all order lines in the parcel are moved.", alias="orderLineIds", json_schema_extra={"examples": [["ol_9c1d2e3f"]]})
    carrier_id: Optional[StrictStr] = Field(default=None, description="Carrier for the new shipment. Copied from the original if omitted.", alias="carrierId", json_schema_extra={"examples": ["car_pn_001"]})
    product_id: Optional[StrictStr] = Field(default=None, description="Carrier product for the new shipment. Copied from the original if omitted.", alias="productId", json_schema_extra={"examples": ["prod_mypack_home"]})
    services: Optional[List[StrictStr]] = Field(default=None, description="Service codes for the new shipment. Copied from the original if omitted.", json_schema_extra={"examples": [["A7"]]})
    additional_parameters: Optional[Dict[str, Any]] = Field(default=None, description="Carrier-specific parameters for the new shipment.", alias="additionalParameters", json_schema_extra={"examples": [{"notificationEmail": "anna@example.dk"}]})
    reference: Optional[StrictStr] = Field(default=None, description="Reference for the new shipment. Defaults to the original reference with a suffix.", json_schema_extra={"examples": ["ORDER-1042-split"]})
    __properties: ClassVar[List[str]] = ["parcelId", "orderLineIds", "carrierId", "productId", "services", "additionalParameters", "reference"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SplitShipmentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SplitShipmentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "parcelId": obj.get("parcelId"),
            "orderLineIds": obj.get("orderLineIds"),
            "carrierId": obj.get("carrierId"),
            "productId": obj.get("productId"),
            "services": obj.get("services"),
            "additionalParameters": obj.get("additionalParameters"),
            "reference": obj.get("reference")
        })
        return _obj


