# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TrackShipment200ResponseEventsInner(BaseModel):
    """
    TrackShipment200ResponseEventsInner
    """ # noqa: E501
    id: StrictStr = Field(description="Unique tracking event identifier.", json_schema_extra={"examples": ["trk_7a8b9c0d"]})
    status: StrictStr = Field(description="Normalized tracking status for the event.", json_schema_extra={"examples": ["in_transit"]})
    carrier_status: StrictStr = Field(description="Raw status string reported by the carrier.", alias="carrierStatus", json_schema_extra={"examples": ["INFORMED"]})
    description: Optional[StrictStr] = Field(description="Human-readable description of the event.", json_schema_extra={"examples": ["The shipment is on its way."]})
    location: Optional[StrictStr] = Field(description="Location where the event was registered.", json_schema_extra={"examples": ["København"]})
    occurred_at: StrictStr = Field(description="Timestamp when the event occurred.", alias="occurredAt", json_schema_extra={"examples": ["2026-06-22T14:30:00.000Z"]})
    __properties: ClassVar[List[str]] = ["id", "status", "carrierStatus", "description", "location", "occurredAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['created', 'awaiting_pickup', 'picked_up', 'in_transit', 'out_for_delivery', 'ready_for_pickup', 'delivered', 'returned', 'exception']):
            raise ValueError("must be one of enum values ('created', 'awaiting_pickup', 'picked_up', 'in_transit', 'out_for_delivery', 'ready_for_pickup', 'delivered', 'returned', 'exception')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrackShipment200ResponseEventsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['location'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrackShipment200ResponseEventsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "carrierStatus": obj.get("carrierStatus"),
            "description": obj.get("description"),
            "location": obj.get("location"),
            "occurredAt": obj.get("occurredAt")
        })
        return _obj


