# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateOrgRequest(BaseModel):
    """
    UpdateOrgRequest
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Organization name", json_schema_extra={"examples": ["Nordic Logistics ApS"]})
    slug: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Organization slug", json_schema_extra={"examples": ["nordic-logistics"]})
    description: Optional[StrictStr] = Field(default=None, description="Organization description", json_schema_extra={"examples": ["Parcel and freight logistics across the Nordics"]})
    currency: Optional[StrictStr] = Field(default=None, description="Billing currency (ISO 4217 code)", json_schema_extra={"examples": ["DKK"]})
    vat_number: Optional[StrictStr] = Field(default=None, description="Company VAT/tax ID for invoices", alias="vatNumber", json_schema_extra={"examples": ["DK12345678"]})
    overage_enabled: Optional[StrictBool] = Field(default=None, description="Allow shipments beyond plan limit (overage charges apply)", alias="overageEnabled", json_schema_extra={"examples": [False]})
    billing_email: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Billing email for invoices", alias="billingEmail", json_schema_extra={"examples": ["billing@nordic-logistics.dk"]})
    company_name: Optional[StrictStr] = Field(default=None, description="Legal company name", alias="companyName", json_schema_extra={"examples": ["Nordic Logistics ApS"]})
    address_line1: Optional[StrictStr] = Field(default=None, description="Address line 1", alias="addressLine1", json_schema_extra={"examples": ["Havnegade 12"]})
    address_line2: Optional[StrictStr] = Field(default=None, description="Address line 2", alias="addressLine2", json_schema_extra={"examples": ["3. sal"]})
    city: Optional[StrictStr] = Field(default=None, description="City", json_schema_extra={"examples": ["København"]})
    postal_code: Optional[StrictStr] = Field(default=None, description="Postal code", alias="postalCode", json_schema_extra={"examples": ["1058"]})
    country: Optional[StrictStr] = Field(default=None, description="Country (ISO 3166-1 alpha-2 code)", json_schema_extra={"examples": ["DK"]})
    customs: Optional[Dict[str, StrictStr]] = Field(default=None, description="Organization-wide customs identifiers (EORI, IOSS, VOEC, etc.); null clears all")
    __properties: ClassVar[List[str]] = ["name", "slug", "description", "currency", "vatNumber", "overageEnabled", "billingEmail", "companyName", "addressLine1", "addressLine2", "city", "postalCode", "country", "customs"]

    @field_validator('slug', mode="before")
    def slug_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[a-z0-9-]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9-]+$/")
        return value

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DKK', 'EUR', 'USD', 'GBP', 'SEK', 'NOK']):
            raise ValueError("must be one of enum values ('DKK', 'EUR', 'USD', 'GBP', 'SEK', 'NOK')")
        return value

    @field_validator('billing_email', mode="before")
    def billing_email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(?!\.)(?!.*\.\.)([A-Za-z0-9_\'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$", value):
            raise ValueError(r"must validate the regular expression /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateOrgRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if vat_number (nullable) is None
        # and model_fields_set contains the field
        if self.vat_number is None and "vat_number" in self.model_fields_set:
            _dict['vatNumber'] = None

        # set to None if billing_email (nullable) is None
        # and model_fields_set contains the field
        if self.billing_email is None and "billing_email" in self.model_fields_set:
            _dict['billingEmail'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['companyName'] = None

        # set to None if address_line1 (nullable) is None
        # and model_fields_set contains the field
        if self.address_line1 is None and "address_line1" in self.model_fields_set:
            _dict['addressLine1'] = None

        # set to None if address_line2 (nullable) is None
        # and model_fields_set contains the field
        if self.address_line2 is None and "address_line2" in self.model_fields_set:
            _dict['addressLine2'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict['postalCode'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if customs (nullable) is None
        # and model_fields_set contains the field
        if self.customs is None and "customs" in self.model_fields_set:
            _dict['customs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateOrgRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "description": obj.get("description"),
            "currency": obj.get("currency"),
            "vatNumber": obj.get("vatNumber"),
            "overageEnabled": obj.get("overageEnabled"),
            "billingEmail": obj.get("billingEmail"),
            "companyName": obj.get("companyName"),
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "city": obj.get("city"),
            "postalCode": obj.get("postalCode"),
            "country": obj.get("country"),
            "customs": obj.get("customs")
        })
        return _obj


