# coding: utf-8

"""
    Zippendo Public API

    Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

    The version of the OpenAPI document: 1.0.0
    Contact: support@zippendo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from zippendo.models.create_order_request_order_lines_inner import CreateOrderRequestOrderLinesInner
from zippendo.models.create_order_request_shipping_address import CreateOrderRequestShippingAddress
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateOrderRequest(BaseModel):
    """
    UpdateOrderRequest
    """ # noqa: E501
    order_number: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Human-readable order number.", alias="orderNumber", json_schema_extra={"examples": ["#1042"]})
    customer_name: Optional[StrictStr] = Field(default=None, description="Customer full name.", alias="customerName", json_schema_extra={"examples": ["Anna Jensen"]})
    customer_email: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Customer email address.", alias="customerEmail", json_schema_extra={"examples": ["anna@example.dk"]})
    shipping_address: Optional[CreateOrderRequestShippingAddress] = Field(default=None, alias="shippingAddress")
    order_lines: Optional[Annotated[List[CreateOrderRequestOrderLinesInner], Field(min_length=1)]] = Field(default=None, description="Line items in the order.", alias="orderLines")
    subtotal_amount: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Order subtotal before shipping and tax.", alias="subtotalAmount", json_schema_extra={"examples": [998]})
    total_amount: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Order grand total.", alias="totalAmount", json_schema_extra={"examples": [1047]})
    currency: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=3)]] = Field(default=None, description="ISO 4217 currency code.", json_schema_extra={"examples": ["DKK"]})
    notes: Optional[StrictStr] = Field(default=None, description="Free-form internal notes.", json_schema_extra={"examples": ["Leave at front desk"]})
    status: Optional[StrictStr] = Field(default=None, description="Order fulfilment status derived from its shipments.", json_schema_extra={"examples": ["processing"]})
    shipping_rule_id: Optional[StrictStr] = Field(default=None, description="ID of the shipping rule to apply.", alias="shippingRuleId", json_schema_extra={"examples": ["clz9k2f0a0002abcd5678ijkl"]})
    __properties: ClassVar[List[str]] = ["orderNumber", "customerName", "customerEmail", "shippingAddress", "orderLines", "subtotalAmount", "totalAmount", "currency", "notes", "status", "shippingRuleId"]

    @field_validator('customer_email', mode="before")
    def customer_email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(?!\.)(?!.*\.\.)([A-Za-z0-9_\'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$", value):
            raise ValueError(r"must validate the regular expression /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'processing', 'partially_fulfilled', 'fulfilled', 'error', 'cancelled']):
            raise ValueError("must be one of enum values ('pending', 'processing', 'partially_fulfilled', 'fulfilled', 'error', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateOrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of shipping_address
        if self.shipping_address:
            _dict['shippingAddress'] = self.shipping_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in order_lines (list)
        _items = []
        if self.order_lines:
            for _item_order_lines in self.order_lines:
                if _item_order_lines:
                    _items.append(_item_order_lines.to_dict())
            _dict['orderLines'] = _items
        # set to None if customer_name (nullable) is None
        # and model_fields_set contains the field
        if self.customer_name is None and "customer_name" in self.model_fields_set:
            _dict['customerName'] = None

        # set to None if customer_email (nullable) is None
        # and model_fields_set contains the field
        if self.customer_email is None and "customer_email" in self.model_fields_set:
            _dict['customerEmail'] = None

        # set to None if shipping_address (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_address is None and "shipping_address" in self.model_fields_set:
            _dict['shippingAddress'] = None

        # set to None if subtotal_amount (nullable) is None
        # and model_fields_set contains the field
        if self.subtotal_amount is None and "subtotal_amount" in self.model_fields_set:
            _dict['subtotalAmount'] = None

        # set to None if total_amount (nullable) is None
        # and model_fields_set contains the field
        if self.total_amount is None and "total_amount" in self.model_fields_set:
            _dict['totalAmount'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if shipping_rule_id (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_rule_id is None and "shipping_rule_id" in self.model_fields_set:
            _dict['shippingRuleId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateOrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orderNumber": obj.get("orderNumber"),
            "customerName": obj.get("customerName"),
            "customerEmail": obj.get("customerEmail"),
            "shippingAddress": CreateOrderRequestShippingAddress.from_dict(obj["shippingAddress"]) if obj.get("shippingAddress") is not None else None,
            "orderLines": [CreateOrderRequestOrderLinesInner.from_dict(_item) for _item in obj["orderLines"]] if obj.get("orderLines") is not None else None,
            "subtotalAmount": obj.get("subtotalAmount"),
            "totalAmount": obj.get("totalAmount"),
            "currency": obj.get("currency"),
            "notes": obj.get("notes"),
            "status": obj.get("status"),
            "shippingRuleId": obj.get("shippingRuleId")
        })
        return _obj


